### ISSUE TITLE
1.3.1 in latest CLion crashes:

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#105]
8:47:47 PM StringIndexOutOfBoundsException: String index out of range: -4
8:48:44 PM NoClassDefFoundError: com/vladsch/idea/multimarkdown/editor/split/UIUtils

**Comment by tamboril** [comment]
I deleted this out of the other bug's comments, but it is an issue.
I tried changing from WebView to Swing with the same results.
It seems to be trying to open a split view, even though I don't have the enhanced version.

**Comment by tamboril** [comment]
This is on CentOS 7.

Here is a big chunk of the stack trace:

    com/intellij/structuralsearch/plugin/ui/UIUtil
    java.lang.NoClassDefFoundError: com/intellij/structuralsearch/plugin/ui/UIUtil
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.vladsch.idea.multimarkdown.editor.split.SplitEditorToolbar.<init>(SplitEditorToolbar.java:83)
	at com.vladsch.idea.multimarkdown.editor.split.SplitFileEditor.createComponent(SplitFileEditor.java:106)
	at com.vladsch.idea.multimarkdown.editor.split.SplitFileEditor.<init>(SplitFileEditor.java:80)
	at com.vladsch.idea.multimarkdown.editor.MarkdownSplitEditor.<init>(MarkdownSplitEditor.java:34)
	at com.vladsch.idea.multimarkdown.editor.MarkdownSplitEditorProvider.createSplitEditor(MarkdownSplitEditorProvider.java:45)
	at com.vladsch.idea.multimarkdown.editor.split.SplitTextEditorProvider$1.build(SplitTextEditorProvider.java:84)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:873)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2337)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:855)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:789)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$10.run(FileEditorManagerImpl.java:769)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:766)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:707)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:151)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$16.run(FileEditorManagerImpl.java:1143)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1139)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openTextEditor(FileEditorManagerImpl.java:1204)
	at com.intellij.ide.actions.OpenFileAction.openFile(OpenFileAction.java:134)
	at com.intellij.ide.actions.OpenFileAction.a(OpenFileAction.java:107)
	at com.intellij.ide.actions.OpenFileAction.access$000(OpenFileAction.java:50)
	at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:68)
	at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:58)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:159)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:111)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:89)
	at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

**Comment by vsch** [comment]
@tamboril, even non-enhanced is using the split editor but without the split. I am in the process of verifying which classes are missing and what extras are trying to be loaded unnecessarily that CLion does not have.

**Comment by vsch** [comment]
@tamboril, it was a dumb error. I was using some classes from OpenAPI that is missing from older IDEs and CLion. When I discovered that they are missing from general distribution, I copied the two functions that I actually need to my own class. Great, all works, except I forgot to remove inheritance in my class from the original class. So it was trying to pull in the original class anyway.

Here is a build with this issue fixed. You will need to download it and install from plugin from disk. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.1.2.zip>

Please let me know if it works for you.

**Comment by vsch** [comment]
same as #104

**Comment by tamboril** [comment]
Thanks, Vlad.  That fixed it.

John

**Comment by vsch** [comment]
@tamboril my pleasure. Sorry I didn't catch myself but in my defense with almost a dozen JetBrains products, all major OS varieties, Java versions and product versions I cannot test every combination. I will add CLion to the list of ones I test because it seems to be missing Java related classes that PhpStorm, PyCharm and WebStorm do have. 

Have yourself a great holiday season.
