### ISSUE TITLE
Version 1.3.2 is not compatible with JDK versions preceding 1.8

### ISSUE THREAD

**Issue by tsillan** [vsch/idea-multimarkdown#110]
Not 100% sure at which point the problem started appearing. Running on OS X 10.10.5.

Two exceptions appear. Reinstalling the plugin (1.3.2) did not help.

The first one looks like the plugin is now expecting Java 8 but my IDE is running on JRE 1.6.0_65 bundled with the IDE. And the second one is probably a consequence of the first one.

**First one:**

java/util/function/Consumer
java.lang.NoClassDefFoundError: java/util/function/Consumer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings.getScriptProviders(MarkdownCssSettings.kt:102)
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings.getCssResources(MarkdownCssSettings.kt:145)
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion.injectHtmlText(MarkdownCssSettings.kt:196)
	at com.vladsch.idea.multimarkdown.settings.MarkdownRenderingProfile.injectHtmlText(MarkdownRenderingProfile.kt:74)
	at com.vladsch.idea.multimarkdown.editor.util.HtmlGenerator.<init>(HtmlGenerator.kt:40)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.<init>(SwingHtmlGenerator.kt:38)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGeneratorProvider.createHtmlGenerator(SwingHtmlGeneratorProvider.kt:39)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor$HtmlUpdater.run(MarkdownPreviewFileEditor.kt:264)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: java.util.function.Consumer PluginClassLoader[com.vladsch.idea.multimarkdown, 1.3.2]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 39 more

**Second one**:

com/vladsch/idea/multimarkdown/settings/MarkdownCssSettings$scriptProviders$1
java.lang.NoClassDefFoundError: com/vladsch/idea/multimarkdown/settings/MarkdownCssSettings$scriptProviders$1
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings.getScriptProviders(MarkdownCssSettings.kt:102)
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings.getCssResources(MarkdownCssSettings.kt:145)
	at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion.injectHtmlText(MarkdownCssSettings.kt:196)
	at com.vladsch.idea.multimarkdown.settings.MarkdownRenderingProfile.injectHtmlText(MarkdownRenderingProfile.kt:74)
	at com.vladsch.idea.multimarkdown.editor.util.HtmlGenerator.<init>(HtmlGenerator.kt:40)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.<init>(SwingHtmlGenerator.kt:38)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGeneratorProvider.createHtmlGenerator(SwingHtmlGeneratorProvider.kt:39)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor$HtmlUpdater.run(MarkdownPreviewFileEditor.kt:264)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by obestwalter** [comment]
Same problem here with Pycharm 5.0.3.

**Comment by tsillan** [comment]
Upgrading to IntelliJ IDEA 15 that comes bundled with JRE 1.8 solved my problem.

**Comment by vsch** [comment]
@tsillan, @obestwalter, it seems Kotlin forEach function requires JDK 1.8. I am going to check with JetBrains regarding this because it seems to be the only function in Kotlin that requires JDK above 1.6.

Kotlin is supposed to be 1.6 compatible and so far it has been. I will post a fix version here once I have resolved the issue.

**Comment by vsch** [comment]
@tsillan, @obestwalter, I looked at more of the code and there are a few Java methods missing in 1.6 that the current code requires. I will document the need for JDK 1.8 until I can figure out a workaround or make it a requirement.

To be honest, supporting 1.6 compatibility is a real pain. I wish I could drop it and make 1.8 the lower limit.

**Comment by vsch** [comment]
@obestwalter, @tsillan please download and install from disk <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.2.1.zip>

JDK 1.6 incompatibilities were removed.

**Comment by obestwalter** [comment]
@vsch Fix works. Thanks!

**Comment by vsch** [comment]
@obestwalter you are welcome.

Out of curiosity, why are you using JDK 1.6 with PyCharm 5 or the problem was not JDK 1.6 related?

**Comment by obestwalter** [comment]
@vsch 

    $ java -version
    java version "1.7.0_80"
    Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
    Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

I installed the oracle 7 from this ppa: https://launchpad.net/~webupd8team/+archive/ubuntu/java
My primary development environment is Ubuntu 14.04.

**Comment by vsch** [comment]
@obestwalter, sorry, just assumed that people stuck to 1.6  for backward compatibility reasons or moved up to 1.8 if they were not so constrained. 1.7 is also missing the methods. I will try to keep the new constructs out of the code for a while. ;)

**Comment by obestwalter** [comment]
@vsch I would recommend to align with what Jetbrains requires. they seem to require either 1.6+ or Oracle 1.7+ - depending on the flavour and the operating system. This is weird, but I am not a Java guy, so this might be not weird to you :)  (got this from [Installing and Launching](https://www.jetbrains.com/pycharm/help/installing-and-launching.html)) - looks like 1.6 still needs to be supported.

**Comment by vsch** [comment]
@obestwalter, I agree especially that Java compatibility is weird. Most stable Java version depends on the OS. On OS X it was 1.6 for a while, now it is 1.8u40. Windows is 1.8u51, Ubuntu seems to be 1.7. 

Java was never my preferred language for that reason. Before this plugin, the last time I did major development in Java was in 2000, and we used to call it a "Write once! Debug everywhere!" language.

That is why I am switching over to Kotlin. A beautifully expressive, concise and readable language from JetBrains that runs on JVM 1.6. Just have to learn what to stay away from the third rail of 1.6 incompatible functions.

**Comment by obestwalter** [comment]
> Write once! Debug everywhere!

*giggles* good luck with Kotlin then. I fell in love with Python in 2006 and never looked back. Until now If I had to program for the JVM I thought I would probably look into clojure (I like dynamic typing and functional programming) but Kotlin looks interesting and has by the nature of it's creator good tooling support I guess.
