### ISSUE TITLE
NoSuchMethodError at load time

### ISSUE THREAD

**Issue by la10736** [vsch/idea-multimarkdown#156]
I didn't change anything but when I started PyCharm this morning I found this issue. Let me know if you need more info.

```
java.util.ArrayList.sort(Ljava/util/Comparator;)V
java.lang.NoSuchMethodError: java.util.ArrayList.sort(Ljava/util/Comparator;)V
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.getMatchedRefs(GitHubLinkResolver.kt:522)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.resolve(GitHubLinkResolver.kt:273)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.getLinkTarget(MultiMarkdownLinkRenderer.java:79)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.renderLink(MultiMarkdownLinkRenderer.java:117)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:148)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:210)
	at org.pegdown.ast.ExpImageNode.accept(ExpImageNode.java:33)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:581)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:622)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:629)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:315)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:120)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:90)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.toHtml(SwingHtmlGenerator.kt:54)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor.makeHtmlPage(MarkdownPreviewFileEditor.kt:44)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:422)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:58)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:378)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.NoSuchMethodError: java.util.ArrayList.sort(Ljava/util/Comparator;)V
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.getMatchedRefs(GitHubLinkResolver.kt:522)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.resolve(GitHubLinkResolver.kt:273)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.getLinkTarget(MultiMarkdownLinkRenderer.java:79)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.renderLink(MultiMarkdownLinkRenderer.java:117)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:148)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:210)
	at org.pegdown.ast.ExpImageNode.accept(ExpImageNode.java:33)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:581)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:622)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:629)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:315)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:120)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:90)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.toHtml(SwingHtmlGenerator.kt:54)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor.makeHtmlPage(MarkdownPreviewFileEditor.kt:44)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:422)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:58)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:378)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.NoSuchMethodError: java.util.ArrayList.sort(Ljava/util/Comparator;)V
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.getMatchedRefs(GitHubLinkResolver.kt:522)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.resolve(GitHubLinkResolver.kt:273)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.getLinkTarget(MultiMarkdownLinkRenderer.java:79)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.renderLink(MultiMarkdownLinkRenderer.java:117)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:148)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:210)
	at org.pegdown.ast.ExpImageNode.accept(ExpImageNode.java:33)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:581)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:622)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:629)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:315)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:120)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:90)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.toHtml(SwingHtmlGenerator.kt:54)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor.makeHtmlPage(MarkdownPreviewFileEditor.kt:44)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:422)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:58)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:378)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.NoSuchMethodError: java.util.ArrayList.sort(Ljava/util/Comparator;)V
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.getMatchedRefs(GitHubLinkResolver.kt:522)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.resolve(GitHubLinkResolver.kt:273)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.getLinkTarget(MultiMarkdownLinkRenderer.java:79)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.renderLink(MultiMarkdownLinkRenderer.java:117)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:148)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:210)
	at org.pegdown.ast.ExpImageNode.accept(ExpImageNode.java:33)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:581)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:622)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:629)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:315)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildrenSkipFirst(ToHtmlSerializer.java:608)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:596)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:120)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:90)
	at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlGenerator.toHtml(SwingHtmlGenerator.kt:54)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor.makeHtmlPage(MarkdownPreviewFileEditor.kt:44)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:422)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:58)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:378)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by vsch** [comment]
@la10736, this would be caused by an update in the Kotlin runtime libraries. The last few Kotlin updates have flip-flopped on what form of .sort() invocation from Kotlin code is supported and I suspect that something caused the runtime Kotlin libraries to be updated, otherwise you would have consistently seen this exception.

I am trying a few different ways to get around this issue and will produce a fix build as soon as I have it working.

**Comment by vsch** [comment]
@la10736, the latest release should address this issue. Please let me know if the issue persists.

**Comment by la10736** [comment]
Fixed.
Thank you!
