### ISSUE TITLE
IllegalStateException when opening settings

### ISSUE THREAD

**Issue by faltrock-abone** [vsch/idea-multimarkdown#160]
State: fresh installation of PHPStorm & MultiMarkdown plugin on FreeBSD 10.2.

When opening the plugin's settings in Settings > Languages & Frameworks > MultiMarkdown the following Exception occurs and prevents the "Loading ..." from disappearing, though the UI elements are active and can be changed.

```
[ 372375]  ERROR - pplication.impl.LaterInvocator - Should be selected always 
java.lang.IllegalStateException: Should be selected always
        at com.vladsch.idea.multimarkdown.settings.MarkdownPreviewSettingsForm.getPreviewSettings(MarkdownPreviewSettingsForm.java:369)
        at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettingsForm.getPreviewSettings(MarkdownApplicationSettingsForm.java:100)
        at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationConfigurable.isModified(MarkdownApplicationConfigurable.java:89)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:175)
        at com.intellij.openapi.options.newEditor.SettingsEditor.a(SettingsEditor.java:414)
        at com.intellij.openapi.options.newEditor.SettingsEditor.b(SettingsEditor.java:408)
        at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:396)
        at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:187)
        at com.intellij.openapi.options.newEditor.ConfigurableEditor$5.run(ConfigurableEditor.java:254)
        at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
        at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
        at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:117)
        at com.intellij.ui.CardLayoutPanel.access$100(CardLayoutPanel.java:37)
        at com.intellij.ui.CardLayoutPanel$1$1.run(CardLayoutPanel.java:131)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
        at java.awt.Dialog.show(Dialog.java:1084)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
        at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1638)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1587)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:118)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[ 372376]  ERROR - pplication.impl.LaterInvocator - PhpStorm 10.0.3  Build #PS-143.1770 
[ 372376]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_66 
[ 372376]  ERROR - pplication.impl.LaterInvocator - VM: OpenJDK 64-Bit Server VM 
[ 372376]  ERROR - pplication.impl.LaterInvocator - Vendor: Oracle Corporation 
[ 372376]  ERROR - pplication.impl.LaterInvocator - OS: FreeBSD 
[ 372376]  ERROR - pplication.impl.LaterInvocator - Last Action: ShowSettings
```

After pasting in the license code, the settings can be saved with "OK" but not "Apply". Re-opening the MultiMarkdown settings does not throw the exception and everything appears normal.

**Comment by vsch** [comment]
@faltrock-abone, thank you for reporting this. I will take care of it.
