### ISSUE TITLE
NoSuchMethodError when typing text

### ISSUE THREAD

**Issue by davidschreiber** [vsch/idea-multimarkdown#167]
Affected versions: 1.4.5 & 1.4.6 (not tested prior to that).

Having editor and preview open side by side (Pressed "Show editor and preview"). Writing text in an existing markdown file won't update the preview but throw this error.

```
java.lang.Integer.min(II)I
java.lang.NoSuchMethodError: java.lang.Integer.min(II)I
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfoKt.isMirrored(CaretContextInfo.kt:927)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.AutoCharsContext$Companion.getContext(CaretContextInfo.kt:898)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfo.getAutoCharsContext(CaretContextInfo.kt:83)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TypedCharHandler.charTyped(TypedCharHandler.kt:103)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:220)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:148)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:90)
	at com.jetbrains.cidr.lang.formatting.OCAutoFormatTypedHandler.execute(OCAutoFormatTypedHandler.java:43)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1355)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1$1.run(TypedAction.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1.run(TypedAction.java:147)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler.execute(TypedAction.java:139)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:133)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1148)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5396)
	at com.intellij.openapi.editor.impl.EditorImpl$10.keyTyped(EditorImpl.java:976)
	at java.awt.Component.processKeyEvent(Component.java:6369)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2809)
	at java.awt.Component.processEvent(Component.java:6191)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:722)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:623)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



java.lang.NoSuchMethodError: java.lang.Integer.min(II)I
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfoKt.isMirrored(CaretContextInfo.kt:927)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.AutoCharsContext$Companion.getContext(CaretContextInfo.kt:898)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfo.getAutoCharsContext(CaretContextInfo.kt:83)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TypedCharHandler.charTyped(TypedCharHandler.kt:103)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:220)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:148)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:90)
	at com.jetbrains.cidr.lang.formatting.OCAutoFormatTypedHandler.execute(OCAutoFormatTypedHandler.java:43)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1355)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1$1.run(TypedAction.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1.run(TypedAction.java:147)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler.execute(TypedAction.java:139)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:133)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1148)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5396)
	at com.intellij.openapi.editor.impl.EditorImpl$10.keyTyped(EditorImpl.java:976)
	at java.awt.Component.processKeyEvent(Component.java:6369)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2809)
	at java.awt.Component.processEvent(Component.java:6191)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:722)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:623)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by davidschreiber** [comment]
Happens every time I write something in the editor. Preview is never updated.

**Comment by vsch** [comment]
@davidschreiber, it could be Java version issue. What JRE version are you running with?

In the mean time I will eliminate the use of min function and make a quick fix version so you can try it out. I suspect that this is the cause.

**Comment by davidschreiber** [comment]
It's 1.6. Here is the Android Studio about screen.
![mainactivity_java_-_android_-____pspdfkit_git_repositories_pspdfkit_android__-_android_studio_2_0_beta_5](https://cloud.githubusercontent.com/assets/1101857/13248757/808b5260-da20-11e5-9cea-c8b698500405.jpg)

**Comment by vsch** [comment]
@davidschreiber, the min function I think appeared in Java 1.7. Here is a version that does not use it. Please let me know if it fixes the problem for you. 

Please download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.6.2.zip>

**Comment by davidschreiber** [comment]
@vsch I can confirm that this version fixed the issue. The error is gone and the preview is updated as expected. Thanks for the fast response.

**Comment by vsch** [comment]
@davidschreiber, please keep in mind that JavaFX WebView preview will not work on JRE less than 1.8. Preferably 1.8u51 or newer. The Swing based preview will work. It has better performance but less rendering capabilities since JavaScript and a lot of HTML/CSS is not supported.

I am running on OS X with the bundled JVM 1.8 from JetBrains with JavaFX overlay that the plugin will offer to download and install if it detects you are running under JetBrains bundled JDK. I find the rendering of text with the Bundled JDK is superior. You may want to check out how I created a copy of the Bundled JDK combined with JavaFX and some missing Oracle distribution native libraries to get full functioning JDK but with JetBrains bug fixes and superior text rendering here: <https://vladsch.com/blog/13>

**Comment by davidschreiber** [comment]
@vsch Thanks for the info. I'll look into it. Do you know if bundling custom JREs is also expected to work with Android Studio?

**Comment by vsch** [comment]
@davidschreiber, I have not tried it but don't see why it would not. 1.6 is so buggy that I am surprised it works. Even apple requires newer OS releases to get version 1.6 as a special operation. Android studio is just a custom labeled IDEA CE with some extra plugins and some branding.

Is Android studio available with the bundled JDK? If not take a look at the blog link. You can download IDEA CE (Community Edition) for OS X and use the bundled JDK from its distribution to create the best OS X JDK for use with JetBrains products, without any of the limitation that the bundled JDK suffers from (lack of media support for WebView because of the missing native libraries from the Bundled JDK)

BTW, thank you for bringing the issue to my attention. It helped me realize that somehow, Java target version on the project was changed to 8 from 6, which I always use as the target for 1.6 JDK.

This is the reason that the use of 1.7 functions was not caught by the compiler.

**Comment by davidschreiber** [comment]
Sadly Android Studio does not bundle its own JDK, very annoying on Macs (especially the font rendering). Also several of the changes available in Android Studio Canary which I'm using are not available inside IDEA CE, so a switch is not possible for me right now. Actually, I'm hoping that Google will soon grab up JRE bundling on Mac and provide a proper 1.8 anytime soon.

**Comment by vsch** [comment]
@davidschreiber, if you create your own JDK as I do in my blog post you can use it with with Android studio by configuring your "custom" JDK as the boot JDK. No need to wait for the bundled version. The only thing you use the IDEA CE is to copy the bundled JDK that comes with it to create your own. After that your "customized" JDK can be used as a 1.8 JDK, with great text rendering and full JavaFX support.
