### ISSUE TITLE
FileNotFoundException: /META-INF/version-notes.xml (No such file or directory)

### ISSUE THREAD

**Issue by natros** [vsch/idea-multimarkdown#170]
I'm getting this in idea.log every time I start IJ 
```
2016-02-27 18:24:00,707 [   1559]   INFO - llij.ide.plugins.PluginManager - Cannot load /Users/fsousa/Library/Application Support/IntelliJIdea15/idea-multimarkdown 
com.intellij.util.xmlb.XIncludeException: java.io.FileNotFoundException: /META-INF/version-notes.xml (No such file or directory)
	at com.intellij.util.xmlb.JDOMXIncluder.parseRemote(JDOMXIncluder.java:344)
	at com.intellij.util.xmlb.JDOMXIncluder.resolveXIncludeElement(JDOMXIncluder.java:231)
	at com.intellij.util.xmlb.JDOMXIncluder.resolveNonXIncludeElement(JDOMXIncluder.java:358)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:192)
	at com.intellij.util.xmlb.JDOMXIncluder.doResolve(JDOMXIncluder.java:177)
	at com.intellij.util.xmlb.JDOMXIncluder.doResolve(JDOMXIncluder.java:99)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:84)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:80)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:172)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:168)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:181)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptorFromDir(PluginManagerCore.java:650)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptor(PluginManagerCore.java:706)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:816)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:805)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:999)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:1155)
	at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:1334)
	at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:105)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:328)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: /META-INF/version-notes.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at com.intellij.util.io.URLUtil.openStream(URLUtil.java:58)
	at com.intellij.util.io.URLUtil.openResourceStream(URLUtil.java:64)
	at com.intellij.openapi.util.JDOMUtil.loadResourceDocument(JDOMUtil.java:363)
	at com.intellij.util.xmlb.JDOMXIncluder.parseRemote(JDOMXIncluder.java:322)
	... 43 more
```

IntelliJ IDEA 15.0.4
Build #IU-143.2287, built on February 23, 2016
JRE: 1.8.0_74-b02 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
OSX

**Comment by vsch** [comment]
@natros, this is caused by having the plugin.xml split into several files that are included from the main file. The relevant plugin code finds the included files properly however other parts do not.

This started with version 16 a few releases ago. I copied the methodology from intellij-community code and it works in every other respect. I will have to figure out how to properly do an include into plugin.xml so that the error does not occur. For now you can safely ignore the error. It does not affect operation other than at startup.
