### ISSUE TITLE
Exception: Panel is guaranteed to be not null now

### ISSUE THREAD

**Issue by mfn** [vsch/idea-multimarkdown#176]
No idea how to reproduce this, found it in PhpStorms error bag:
```
Panel is guaranteed to be not null now
java.lang.IllegalStateException: Panel is guaranteed to be not null now
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.getPanelGuaranteed(PreviewFileEditorBase.kt:327)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:432)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:59)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:379)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Using PhpStorm PS-145.256.26
Build #PS-145.256, built on March 9, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by zenweasel** [comment]
Also receiving this error on startup every time in WebStorm. I have purchased the enhanced version.

WebStorm 2016.1
Build #WS-145.258, built on March 16, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by breandan** [comment]
Same issue running AceJump 1.4.7 on IntelliJ IDEA 2016.1, here's my build information:

>Build #IU-145.257, built on March 15, 2016
>JRE: 1.8.0_40-release-b132 x86_64
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by vsch** [comment]
I am able to duplicate this in WebStorm and trying to do the same in IDEA. I will post a fix as soon as it is available.

**Comment by vsch** [comment]
@mfn, @zenweasel, @breandan, fix available. Please download and install from disk.

Please let me know if it works.

<https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.7.4.zip>
