### ISSUE TITLE
Panel is guaranteed to be not null

### ISSUE THREAD

**Issue by derkan** [vsch/idea-multimarkdown#186]
Hi,

PyCharm couldn't load with following error:
```
Panel is guaranteed to be not null now
java.lang.IllegalStateException: Panel is guaranteed to be not null now
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.getPanelGuaranteed(PreviewFileEditorBase.kt:327)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:432)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:59)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$$inlined$synchronized$lambda$1.run(PreviewFileEditorBase.kt:379)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by obestwalter** [comment]
FWIW - I keep having that error in PyCharm 2016.1 Why did you close it again?

**Comment by derkan** [comment]
#176 same issue.

**Comment by obestwalter** [comment]
Thanks. And it's fixed already!

**Comment by vsch** [comment]
Please download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.7.10.zip>

This build has the same fix in the preview tab not just in the split editor as the 1.4.7.4 build in #176 .

**Comment by obestwalter** [comment]
works like a [py]charm - thanks!
