### ISSUE TITLE
javafx/embed/swing/JFXPanel : Unsupported major.minor version 52.0 [Plugin: com.vladsch.idea.multimarkdown]

### ISSUE THREAD

**Issue by wys1010** [vsch/idea-multimarkdown#21]
javafx/embed/swing/JFXPanel : Unsupported major.minor version 52.0 [Plugin: com.vladsch.idea.multimarkdown]
com.intellij.diagnostic.PluginException: javafx/embed/swing/JFXPanel : Unsupported major.minor version 52.0 [Plugin: com.vladsch.idea.multimarkdown]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:266)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditorProvider.createEditor(MultiMarkdownFxPreviewEditorProvider.java:115)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditorProvider.createEditor(MultiMarkdownFxPreviewEditorProvider.java:105)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$12.run(FileEditorManagerImpl.java:859)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2369)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:842)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:776)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9.run(FileEditorManagerImpl.java:756)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
![20150909095446](https://cloud.githubusercontent.com/assets/6057375/9751554/dc568f68-56d8-11e5-96fe-911de1117a77.png)

**Comment by vsch** [comment]
Thank you for reporting this.

This means you are running the IDEA with JDK 1.6 and the plugin was compiled for 1.8. I will double check that because normally I always stick to 1.6 level for compilation.

However, to get the new preview the latest release requires that your IDEA boot JDK is 1.8. JavaFX WebView requires it.

You can continue to use the previous version which you can download from the [Official JetBrains plugin site Version 1.0.24](https://plugins.jetbrains.com/plugin/download?pr=&updateId=21191).

I'll verify if it was compiled for 1.8 and correct it for the next release so that it will work with JDK 1.6, if I can.

**Comment by wys1010** [comment]
Thank you, I have a lot of help.

**Comment by FDiskas** [comment]
Same problem, thanks for help

**Comment by mfn** [comment]
Same problem, thanks for help too.

**Comment by vsch** [comment]
New version released. Will run with JDK 1.6.

**Comment by kelvin0mql** [comment]
Are we certain that it didn't also cause a problem with JDK 1.7? This linux workstation has been 1.7 for a couple years, long before I ever even heard of intellij... yet I had this exact exception with MultiMarkdown 1.1.0.

**Comment by vsch** [comment]
New release available 1.1.2:
- Fix Exception reporting for ScratchFileService not found on older versions. If the check fails then no others will be performed until build of IDE changes.
- Fix WebView Preview Tab not working for 1.8u60 and up. In 1.8u60+ it no longer handles fonts with uri(data:) nor font/woff only .ttf.
- Fix allowing capital X to mark closed tasks. Fix #24
- Fix lack of ComboBox for Build 133.1711, now for earlier builds using List for theme selection instead of ComboBox.
- Change since-build to 133.1711, earliest tested version IDEA 13.0 CE, new Preview is not available but old preview works.

Please let me know if it solves your issue and/or close the issue which will be taken as issue solved.
