### ISSUE TITLE
Wrap on typing and Table format do not take actual character widths into account for multi-byte characters

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#223]
**copied from #219**

Table formatting produces unexpected results when typing multibyte characters.
Would you have any plans to fix it?
In case it is difficult to handle multibyes, it would be nice if we could disable auto formatting feature for table.

**Environment:**
* Ubuntu 14.04 LTS
* IntelliJ IDEA 2016.1
* Build #IU-145.970, built on April 18, 2016
* JRE: 1.8.0_76-release-b47 amd64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Multimarkdown: 1.4.10 (Enhanced edition)

**Expected result:**
```
| マルチバイト |
|:-----------|
| Cell       |
```

```
| Alphabet   |
|:-----------|
| マルチバイト |
```

**Actual result:**
```
| マルチバイト |
|:-------|
| Cell   |
```

```
| Alphabet |
|:---------|
| マルチバイト   |
```

**Comment by cuiguojie** [comment]
@vsch both problem with chinese character.

```
| 字段名     | 说明               | 是否必须 | 备注     |
|---------|------------------|------|--------|
| status  | 状态码              | 是    | String |
| result  | 内容主体             | 否    | Object |
| message | 异常情况的错误信息，供显示给用户 | 否    | String |
```

Several years ago I use [vimwiki ](https://github.com/vimwiki/vimwiki) to write docs, it's auto-formatting table feature can work well with both English and CJK characters. 
The syntax of vimwiki is similar to markdown, hope it can help you.

**Comment by cuiguojie** [comment]
and for CJK coder, can suggest them to use some special monospace font, for example I use [inconsolata](http://levien.com/type/myfonts/inconsolata.html). 

with this font, the width of one CJK character equal to two english character. maybe it's easier to calculate the total width than another font like menlo.

![monospace](https://cloud.githubusercontent.com/assets/367154/14980349/6d90c264-115a-11e6-85ad-d5c97e3b51ab.jpg)

**Comment by vsch** [comment]
@cuiguojie, this feature will be implemented soon. I am looking into the performance impact and will most likely have an option to turn off `use actual character width` for wrap on typing and table auto-format for users who prefer speed to visual accuracy.

It is best to use the graphical character width to achieve closest visual alignment needed for table columns, so it should work for any font. Using a font where all character widths are integer multiples will create perfect alignment so your recommendation for a 'monospaced' compatible font will yield best results. 

Once the code is implemented I could use all the help I can get validating the results, being limited to latin and cyrillic languages: English, French and Russian, I won't have sufficient number of use cases to thrash it out.

I will make a stable early implementation available here for everyone willing to help getting the functionality and performance right.

**Comment by cuiguojie** [comment]
@vsch but with the CJK characters like Chinese or Japanese, if the font can't make one character width equal to two latin, it can't align perfect. 

because in the editor we can only use SPACE to fill the table and make it looks prefect, but the width of SPACE equal to one latin character.

this is the the demo I use font 'menlo', you could find that you can't align the ```|```.

![menlo](https://cloud.githubusercontent.com/assets/367154/14981220/3750f9e8-1160-11e6-91b6-37ff33005f7a.png)

**Comment by vsch** [comment]
@cuiguojie yes that will be the limitation if the font characters are not multiples. So it will be up to the user to select a font that gives the best visuals. The plugin will do its best and make sure that the alignment is off by no more than 1/2 the width of a space and in the case of table headers 1/2 the width of a dash `-`.

Even if you will not get perfect alignment it will be the best compromise given a poor choice of fonts. 

Here is one I did by eye. It would be the target result in the implementation:

<img width="456" alt="screen shot 2016-05-03 at 7 51 53 am" src="https://cloud.githubusercontent.com/assets/10299086/14982399/01743710-1104-11e6-9b8a-2f64784142f9.png">

Is not perfect but much better than just assuming Latin character widths:

<img width="455" alt="screen shot 2016-05-03 at 7 52 03 am" src="https://cloud.githubusercontent.com/assets/10299086/14982415/190b610a-1104-11e6-8089-0f1395c3ffab.png">

**Comment by cuiguojie** [comment]
@vsch waiting for the new version :)

**Comment by vsch** [comment]
@cuiguojie, pre-releas EAP version with proper wrapping and table alignment based on character widths is now available: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.92.zip

Table column width matching is done +/- 1/2 space width of the display font, cumulative for the line. 

Please let me know if you encounter any issues.

Here is the result of wrapping and formatting tables for source given below:

<img width="799" alt="screen shot 2016-05-25 at 11 44 01 am" src="https://cloud.githubusercontent.com/assets/10299086/15546565/5cc7f022-226e-11e6-9e8c-04c6d18fb2ae.png">

Source:

    | マルチバイト |
    |:-----------|
    | Cell       |
    
    | Alphabet   |
    |:-----------|
    | マルチバイト |
    
    マルチバイト マルチバイト マルチバイト マルチバイト tests マルチバイト マルチバイト マルチバイト マルチバイト
    マルチバイト マルチバイト
    
    | 字段名   | 说明                         | 是否必须 | 备注    |
    |---------|-----------------------------|---------|--------|
    | status  | 状态码                       | 是       | String |
    | result  | 内容主体                      | 否       | Object |
    | message | 异常情况的错误信息，供显示给用户 | 否       | String |
    
    异常情况的错误信息, mixed chars width wrapping mode test 供显示给用户 异常情况的错误信息 供显示给用户
    异常情况的错误信息，供显示给用户 异常情况的错误信息，供显示给用户 异常情况的错误信息，供显示给用户
    异常情况的错误信息，供显示给用户

**Comment by cuiguojie** [comment]
@vsch 

for this feature, it's perfect with my font setting.

but  the plugin will crash after I tap BACKSPACE continuous in table.

there are some event logs in IDEA

```
12:51:46 AssertionError: Assertion failed
12:51:55 AssertionError: update failed for AnAction with ID=com.vladsch.idea.multimarkdown.editor.actions.styling.ToggleBoldAction: Assertion failed
```

and this is the detail of the **Assertion failed**

```
Assertion failed
java.lang.AssertionError: Assertion failed
	at com.vladsch.idea.multimarkdown.parser.SyntheticNodes$SyntheticNode.<init>(SyntheticNodes.kt:128)
	at com.vladsch.idea.multimarkdown.parser.SyntheticNodes.<init>(SyntheticNodes.kt:66)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1502)
	at org.pegdown.ast.TableCellNode.accept(TableCellNode.java:45)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1863)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:1973)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeChild(LexParserASTVisitor.java:1942)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1904)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1884)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1572)
	at org.pegdown.ast.TableRowNode.accept(TableRowNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1863)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:1976)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeChild(LexParserASTVisitor.java:1942)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1904)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1884)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1451)
	at org.pegdown.ast.TableBodyNode.accept(TableBodyNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1863)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:1973)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1898)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1889)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1437)
	at org.pegdown.ast.TableNode.accept(TableNode.java:63)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1863)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1796)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:388)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParser.parseMarkdown(MultiMarkdownLexParser.java:55)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:174)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:95)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:268)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:194)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:202)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:52)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:83)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.vladsch.idea.multimarkdown.editor.actions.MarkdownActionUtil.getElementsUnderCaretOrSelection(MarkdownActionUtil.kt:139)
	at com.vladsch.idea.multimarkdown.editor.actions.MarkdownActionUtil.getCommonParentOfType(MarkdownActionUtil.kt:101)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction.getCommonParentOfType(BaseToggleStateAction.java:76)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction.getCommonState(BaseToggleStateAction.java:81)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction.isSelected(BaseToggleStateAction.java:105)
	at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:64)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction.update(BaseToggleStateAction.java:90)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:120)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:181)
	at java.awt.Container.addImpl(Container.java:1121)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:308)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:948)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:64)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:173)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:191)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:675)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.i(FocusManagerImpl.java:656)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.c(FocusManagerImpl.java:626)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$11.run(FocusManagerImpl.java:522)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2405)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:500)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:163)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1431)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1421)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1405)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@cuiguojie, I added a test to prevent this, although I was not able to duplicate it. This is due to other changes.

New eap build that should take care of this. https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.94.zip

Please let me know if you encounter anything else.

**Comment by cuiguojie** [comment]
@vsch It will not crash now.

One time when I was editing the table, the setting of **Auto-Format On Typing** was unchecked in the background. but I can't duplicate it.

Maybe there are something can be improved, for example **add row on ENTER**, the cursor is under the new row, not in the first table-cell of it. 

But just for this issue, the format feature with CJK Strings works better than before. and with my font setting it is prefect, like the picture:

![format](https://cloud.githubusercontent.com/assets/367154/15562536/89767480-2332-11e6-98fa-91cad5af6772.png)

**Comment by vsch** [comment]
@cuiguojie, the row insert is supposed to put the cursor in the first cell of the inserted row. I tried it with a default ENTER definition and with my key map which always inserts a new line below the current one, regardless of where the cursor is on the line, and in both cases it seems to work.

With default key map of OS X 10.5+ key map scheme:

![table-insert-row](https://cloud.githubusercontent.com/assets/10299086/15583111/54e692b2-2342-11e6-8521-638d464b1e85.gif)

Can you let me know what action is assigned to the ENTER key in your keymap:

Default:
<img width="827" alt="screen shot 2016-05-26 at 1 05 30 pm" src="https://cloud.githubusercontent.com/assets/10299086/15583164/9d37d4c2-2342-11e6-9471-6dbcea37cd6c.png">

My Mapping:
<img width="1008" alt="screen shot 2016-05-26 at 1 05 52 pm" src="https://cloud.githubusercontent.com/assets/10299086/15583166/a001a052-2342-11e6-9a54-8d4940dd1c81.png">

**Comment by cuiguojie** [comment]
@vsch I use the default key map same with you, and I find the reason at last.

If there is a paragraph and it is too long to be wrapped automatically, all the table after it will have this bug.

and when I was debugging, I got another crash report:

```
subSequence(469, 475) is not within range [0, 469)
java.lang.IndexOutOfBoundsException: subSequence(469, 475) is not within range [0, 469)
	at com.vladsch.smart.SmartCharSequenceBase.checkBounds(SmartCharSequenceBase.kt:319)
	at com.vladsch.smart.SmartCharSequenceBase.subSequence(SmartCharSequenceBase.kt:72)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.textForWrapping(MultiMarkdownPsiImplUtil.java:1058)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.textForWrapping(MultiMarkdownPsiImplUtil.java:1107)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.textForWrapping(MultiMarkdownPsiImplUtil.java:1107)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.textForWrapping(MultiMarkdownPsiImplUtil.java:1107)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.textForWrapping(MultiMarkdownPsiImplUtil.java:1107)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownPsiImplUtil.linesForWrapping(MultiMarkdownPsiImplUtil.java:1025)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$tableChars$2.invoke(TableContext.kt:41)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$tableChars$2.invoke(TableContext.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.getTableChars(TableContext.kt)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:55)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.getTable(TableContext.kt)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.canDeleteRow(TableContext.kt:87)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.DeleteRowAction.canPerformAction(DeleteRowAction.kt:22)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseTableAction.update(BaseTableAction.kt:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:120)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:181)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:202)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addNotify(JBTabsImpl.java:478)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1121)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addImpl(JBTabsImpl.java:2719)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateContainer(JBTabsImpl.java:2693)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:921)
	at com.intellij.ui.tabs.impl.JBTabsImpl.access$2100(JBTabsImpl.java:68)
	at com.intellij.ui.tabs.impl.JBTabsImpl$14.run(JBTabsImpl.java:882)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$1$1.run(EditorTabbedContainer.java:140)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$1.execute(EditorTabbedContainer.java:136)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:878)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:869)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:90)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@cuiguojie, can you make the markdown file that has "If there is a paragraph and it is too long to be wrapped automatically, all the table after it will have this bug." available to me for debugging?

It seems there is a parser bug that is exposed by that file.

**Comment by cuiguojie** [comment]
@vsch it's not about which file,  I can make this bug (not the crash) with any file, with two condition:

* checked **Use soft wraps in editor**
* type a long sentence before the table

for example, I copy some stuff in your site and append a table after it:

```
Available special offer with the lowest price will be used during checkout. Each special offer is valid until promotion expiration or all promotional licenses have been claimed, after which the next best special will be used. When all promotional licenses are gone, regular price will be applied.

| title   |
|---------|
| content |
```

you can try with this mock doc, and press ENTER in the table.

**Comment by vsch** [comment]
@cuiguojie, thank you for catching this. It was caused by using visualPosition instead of logicalPosition in the code for getting the caret position.

Fixed in EAP patch release 1.6.3.98: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.98.zip>

I am not sure yet that the multi-byte wrapping and table formatting code will work correctly if soft wraps are on. I will have to double check.

**Comment by cuiguojie** [comment]
@vsch It works well in my IDEA now.

The table auto formatting feature is not friendly when typing Chinese, because maybe  you use the keydown event to trigger the formatting, but not like typing English that one press one character, we have to type some letter and then select the word what we want. 

It like counting the number of letters when post a twitter, we have to find some way to listen the **change** event of the textarea, not the keydown in javascript.

but at least, I can type a space after the works and then delete it to trigger auto formatting, or use the **reformat element** button. 

I bought the plugin for the table formatting feature, now it works well, thank you.

**Comment by vsch** [comment]
@cuiguojie, I will enable Chinese keyboard input so I can try it out and address this issue.

**Comment by vsch** [comment]
@cuiguojie, fix available. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.100.zip>

I installed `Pinyin - Simplified` input on OS X. This input allows typing multi-word sequences: `ab ` will result in `阿笨` but the IDE typing handler calls do not get generated for multi-word sequences. More single word typing or just typing space/backspace will format the table.

**Comment by cuiguojie** [comment]
@vsch My mean is not typing multi-word sequence one time, in Pinyin input, we have to type the sound of a character first, then select the one form all the characters sounds like it.

for example,  If I want to type ```加``` which means ```add```, I need to type ```jia``` first,  then type the order number ```1``` to select ```加```. 
If I type order number ```2```, the character I got is ```家``` which means ```family```. Both ```加``` and ```家``` have the same pronunciation.  The document would not be changed before I type the order number of the character.

if the IDE can't handler the **change** event of the document, maybe it is impossible to implement the formatting when typing Chinese.

But I can type a space after the character and then delete it to trigger auto formatting :)

**Comment by vsch** [comment]
@cuiguojie, just verified and the IDE does generate typing handler calls when multiple characters are used for a word. 

It was the plugin code that detected an unexpected difference between Psi and Document length that was skipping auto-format. I changed the code to allow negative difference caused by multi-char to single word changes when a character is typed to account for this condition.

<https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.102.zip>
