### ISSUE TITLE
Index out of range: 23252

### ISSUE THREAD

**Issue by aliceinwire** [vsch/idea-multimarkdown#224]
```
Index out of range: 23252
java.lang.IndexOutOfBoundsException: Index out of range: 23252
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:101)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfo.nodeEnd(CaretContextInfo.kt:178)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.ParagraphContext$Companion.paragraphContext(CaretContextInfo.kt:983)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.ParagraphContext$Companion.getContext(CaretContextInfo.kt:903)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.ListItemContext$Companion.getContext(CaretContextInfo.kt:290)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.CaretContextInfo.getListItemContext(CaretContextInfo.kt:95)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.BackspaceHandler.beforeCharDeleted(BackspaceHandler.kt:60)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:95)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:345)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:425)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:327)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by vsch** [comment]
@aliceinwire, thank you for the bug report.

This part of the code has been reworked for performance and robustness for the upcoming release. 1.5.0. 

A patch fix is available which is a release candidate for 1.5.0. You will need to download and install from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.10.32.zip

Long list of fixes and improvements can be found here: [Version Notes](https://github.com/vsch/idea-multimarkdown/blob/master/resources/META-INF/VERSION.md)

An overview of toolbar buttons and new as you type automation features can be found here: [Enhanced Feature Wiki](https://github.com/vsch/idea-multimarkdown/wiki/Enhanced-Features)

If you do give the patch a try please let me know how it resolves your issue.
