### ISSUE TITLE
NPE upon opening simple markdown file

### ISSUE THREAD

**Issue by bbarker** [vsch/idea-multimarkdown#244]
```
null
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.<init>(MultiMarkdownLinkRenderer.java:58)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.<init>(MultiMarkdownPreviewEditor.kt:113)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditorProvider$2.run(MultiMarkdownFxPreviewEditorProvider.java:108)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditorProvider$2.run(MultiMarkdownFxPreviewEditorProvider.java:98)
	at com.vladsch.idea.multimarkdown.settings.FailedBuild$DefaultImpls.runBuild(FailedBuild.kt:44)
	at com.vladsch.idea.multimarkdown.settings.FailedBuildWithJdk$DefaultImpls.runBuild(FailedBuild.kt)
	at com.vladsch.idea.multimarkdown.settings.fxPreviewFailedBuild.runBuild(FailedBuild.kt:80)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditorProvider.createEditor(MultiMarkdownFxPreviewEditorProvider.java:98)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxUnmodifiedHtmlEditorProvider.createEditor(MultiMarkdownFxUnmodifiedHtmlEditorProvider.java:43)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14.run(FileEditorManagerImpl.java:894)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2426)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:876)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:810)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$11.run(FileEditorManagerImpl.java:790)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:787)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:728)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:151)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$17.run(FileEditorManagerImpl.java:1156)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1152)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:146)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:132)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:128)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:115)
	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:982)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:179)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:238)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:248)
	at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:133)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I just had this NPE when opening the following file:

```
# NCRNCornellWebTests
Web tests to check the status of NCRN Cornell Node sites and pages.
```

I will update if the problem reoccurs or proves to be serious - so far it doesn't seem to cause any issue.

**Comment by vsch** [comment]
@bbarker, thank you for let me know of this issue. I added a test for null and made a patch release <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.1.zip>. If you get it again then just download and install plugin from disk and the issue will be resolved.

I was not able to duplicate this so I suspect it is timing dependent during initialization but the code did have a potential of generating a NPE, so I added an explicit test to avoid this in the future.

**Comment by bbarker** [comment]
Great - no worries, I noticed I keep getting them periodically but it
doesn't cause an actual problem for me so far.

On Wed, Jun 1, 2016 at 9:48 AM, Vladimir Schneider <notifications@github.com
> wrote:

> @bbarker <https://github.com/bbarker>, thank you for let me know of this
> issue. I added a test for null and made a patch release
> https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.1.zip.
> If you get it again then just download and install plugin from disk and the
> issue will be resolved.
>
> I was not able to duplicate this so I suspect it is timing dependent
> during initialization but the code did have a potential of generating a
> NPE, so I added an explicit test to avoid this in the future.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vsch/idea-multimarkdown/issues/244#issuecomment-222997743>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA37ji22cqGYXYhGfLDk7RffGU8JazsEks5qHY3HgaJpZM4Iri6T>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by vsch** [comment]
@bbarker, this confirms that it is initialization timing issue. It fails during first init but then second initialization is fine. It probably happens when you open a new project. I noticed that call sequences are different between initialization when IDE opens and when a project is opened.

**Comment by bbarker** [comment]
Ah, yes - I believe I did open a  new project around the time I noticed the
issue.

On Wed, Jun 1, 2016 at 10:51 AM, Vladimir Schneider <
notifications@github.com> wrote:

> @bbarker <https://github.com/bbarker>, this confirms that it is
> initialization timing issue. It fails during first init but then second
> initialization is fine. It probably happens when you open a new project. I
> noticed that call sequences are different between initialization when IDE
> opens and when a project is opened.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vsch/idea-multimarkdown/issues/244#issuecomment-223017420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA37jq_WQTVtaK3A9OZD7WSLs5Fp3u3pks5qHZxpgaJpZM4Iri6T>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com
