### ISSUE TITLE
Error and corrupting files

### ISSUE THREAD

**Issue by jimlongo56** [vsch/idea-multimarkdown#247]
Getting this error whenever I do much of anything in relation to Markdown files.

    1:45:39 PM ArrayIndexOutOfBoundsException: 325

Followed shortly thereafter by

    1:46:04 PM Unable to save plugin settings: The plugin com.vladsch.idea.multimarkdown failed to save settings and has been disabled. Please restart PhpStorm (show balloon)

After reactivating and restarting get error that file foo.md could not be indexed, restart IDE.

Latest version of PHPStorm 

PhpStorm 2016.1.2
Build #PS-145.1616, built on May 24, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by vsch** [comment]
@jimlongo56, if possible can you give me the stack trace from the exception so I can see the context of the error.

In the mean time you can try the latest patch release because there was a similar error fixed in it: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.3.zip

please download and install plugin from disk.

**Comment by jimlongo56** [comment]
@vsch I just installed that new version.

When launching PHPStorm I get this

    error while indexing /Volumes/TopLineDev/TopLineCode/Docs/yola/LanguageSupport.md
    To reindex this file IDEA has to be restarted: 325
    java.lang.ArrayIndexOutOfBoundsException: 325
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1482)
	at org.pegdown.ast.TableBodyNode.accept(TableBodyNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1911)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2021)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1946)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1937)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1475)
	at org.pegdown.ast.TableNode.accept(TableNode.java:63)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1911)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1844)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:388)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParser.parseMarkdown(MultiMarkdownLexParser.java:55)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:174)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:95)
	at com.intellij.lexer.DelegateLexer.start(DelegateLexer.java:39)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexer.start(BaseFilterLexer.java:153)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexerUtil.scanContent(BaseFilterLexerUtil.java:48)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:36)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:32)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1831)
	at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1760)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1703)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vsch** [comment]
@jimlongo56, thank you for the stack trace. The error appears to be another pegdown parser issue. I made a patch release to detect and correct the condition. However, it is source file dependent so I cannot validate if it is validated as solved until you try it out. https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.5.zip

I am in the process of implementing a commonmark-java based parser for the plugin to replace pegdown. If all goes as well as it is going now, the next release at the end of the month will have pegdown replaced and with it all the hanging and slow performance. The new parser is on average 20x faster than pegdown and in pegdown's pathological cases over 1000x faster.

Please let me know if the problem has been solved so I can make the patch available on the EAP channel.

**Comment by jimlongo56** [comment]
Thanks, the issue seems to have been corrected. No more errors.
