### ISSUE TITLE
update failed for AnAction with ID=com.vladsch.idea.multimarkdown.editor.actions.styling.ListTightAction

### ISSUE THREAD

**Issue by johnlindquist** [vsch/idea-multimarkdown#252]
update failed for AnAction with ID=com.vladsch.idea.multimarkdown.editor.actions.styling.ListTightAction
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.psi.impl.PsiImplUtil.nextNonWhiteSpaceSibling(PsiImplUtil.java:234)
	at com.vladsch.idea.multimarkdown.psi.impl.PsiImplUtil.followingBlankLine(PsiImplUtil.java:286)
	at com.vladsch.idea.multimarkdown.psi.impl.PsiImplUtil.followingBlankLine(PsiImplUtil.java:298)
	at com.vladsch.idea.multimarkdown.psi.impl.PsiImplUtil.followingBlankLine(PsiImplUtil.java:298)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.ListItemContext$Companion.tightenListDeleteLines(ListItemContext.kt:667)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.ListItemContext$Companion.canTightenList(ListItemContext.kt:584)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.ListTightAction.isSelected(ListTightAction.kt:29)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.ListToggleStateSelectionAction.isSelected(ListToggleStateSelectionAction.kt:66)
	at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:64)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.ListToggleStateSelectionAction.update(ListToggleStateSelectionAction.kt:80)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:123)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:96)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:942)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:65)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:174)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:101)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:935)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:208)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addNotify(JBTabsImpl.java:471)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1121)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.ui.ThreeComponentsSplitter.setInnerComponent(ThreeComponentsSplitter.java:456)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.setDocumentComponent(ToolWindowsPane.java:421)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$SetEditorComponentCmd.run(ToolWindowsPane.java:1168)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:829)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:357)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vsch** [comment]
@johnlindquist, thank you for the report. I added a few checks for Psi validity before using the elements. I forgot to add these originally and only checked for null, but when the element is no longer valid it will return null for its properties that are never null, unless it is not valid.

I made an eap release with the fixes. Please download and install from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.1.2.zip
