### ISSUE TITLE
AssertionError while indexing .md file

### ISSUE THREAD

**Issue by macdaddyaz** [vsch/idea-multimarkdown#263]
The plugin has been throwing me an AssertionError while indexing one of my Markdown files. It also throws an AssertionError when opening that file. It seems to be related to badly formatted tables. The file contained 2 tables where the last line did not have enough cells defined. I opened it up in a text editor, fixed the formatting, and then Markdown Navigator no longer threw the errors. It seems that plugin should deal with this situation gracefully, rather than crashing.

Error stack trace (during indexing):
```
Error while indexing /home/emcintyre/Development/src/wikis/imp-api.wiki/Backend-Jobs.md
To reindex this file IDEA has to be restarted: Assertion failed
java.lang.AssertionError: Assertion failed
	at com.vladsch.idea.multimarkdown.parser.SyntheticNodes$SyntheticNode.<init>(SyntheticNodes.kt:128)
	at com.vladsch.idea.multimarkdown.parser.SyntheticNodes.<init>(SyntheticNodes.kt:96)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1180)
	at org.pegdown.ast.CodeNode.accept(CodeNode.java:29)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1916)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2026)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeChild(LexParserASTVisitor.java:1995)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1957)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1937)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1550)
	at org.pegdown.ast.TableCellNode.accept(TableCellNode.java:45)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1916)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2026)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeChild(LexParserASTVisitor.java:1995)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1957)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1937)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1618)
	at org.pegdown.ast.TableRowNode.accept(TableRowNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1916)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2029)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeChild(LexParserASTVisitor.java:1995)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1957)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1937)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1494)
	at org.pegdown.ast.TableBodyNode.accept(TableBodyNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1916)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2026)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1951)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1942)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1475)
	at org.pegdown.ast.TableNode.accept(TableNode.java:63)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1916)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1849)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:388)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParser.parseMarkdown(MultiMarkdownLexParser.java:55)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:174)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:95)
	at com.intellij.lexer.DelegateLexer.start(DelegateLexer.java:39)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexer.start(BaseFilterLexer.java:153)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexerUtil.scanContent(BaseFilterLexerUtil.java:48)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:36)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:32)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1831)
	at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1760)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1703)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vsch** [comment]
@macdaddyaz, thank you for the report. It seems pegdown produces a strange AST from the markdown in question.

Since I am in the process of replacing the parser, the issue will be fixed with the new parser. No point in wasting time rearranging deck chairs on the Titanic. ;)
