### ISSUE TITLE
After upgrading to 1.8.3. IntelliJ IDEA 2016.2 hangs immediately after startup

### ISSUE THREAD

**Issue by tan9** [vsch/idea-multimarkdown#278]
Thread dump snippet:
```
"ApplicationImpl pooled thread 11" #99 prio=4 os_prio=31 tid=0x00007fc4daeec800 nid=0x1f37 runnable [0x0000700004705000]
   java.lang.Thread.State: RUNNABLE
	at com.vladsch.idea.multimarkdown.parser.LexParserPegdownASTVisitor.excludeTailBlankLine(LexParserPegdownASTVisitor.java:761)
	at com.vladsch.idea.multimarkdown.parser.LexParserPegdownASTVisitor.visitChildren(LexParserPegdownASTVisitor.java:2237)
	at com.vladsch.idea.multimarkdown.parser.LexParserPegdownASTVisitor.visit(LexParserPegdownASTVisitor.java:417)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at com.vladsch.idea.multimarkdown.parser.MarkdownLexParser.parsePegdownMarkdown(MarkdownLexParser.java:93)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parsePegdown(MultiMarkdownLexParserManager.java:212)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:144)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:139)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:118)
	at com.intellij.lexer.DelegateLexer.start(DelegateLexer.java:39)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexer.start(BaseFilterLexer.java:153)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexerUtil.scanContent(BaseFilterLexerUtil.java:48)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:36)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:32)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:454)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1632)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1558)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$688/84506428.run(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1515)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1500)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.util.indexing.UnindexedFilesUpdater$$Lambda$678/528384013.consume(Unknown Source)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$681/514879722.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$686/1960753483.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

IntelliJ IDEA event log and status bar:

![hang](https://cloud.githubusercontent.com/assets/638068/17044660/c42325a8-4ff4-11e6-899f-03d54f145cc5.png)

**Comment by tan9** [comment]
Manual removing idea-multimarkdown from the plugin directory, my IDEA lives again.

**Comment by vsch** [comment]
@tan9, thank you for bringing this to my attention. It is related to pegdown parsing problem. I have pulled the release and will make a new release that addresses this issue.

Pegdown parser has a lot of issues with some markdown sources.

I am removing pegdown and replacing it with a much faster, predictable and easier to maintain parser, without the parsing issues pegdown has. Only an early preview version is available for now but if you are curios about the typing response with the new parser.  See [Preview With New Parser: Version 1.9.9.4](https://github.com/vsch/idea-multimarkdown2/tree/b1.8.0#preview-with-new-parser-version-1994)

BTW, the preview version is the one I am using in my setup because pegdown is too slow for editing the test case files for the new parser. The HTML rendering is still pegdown, I just turn it off to get full "no pegdown" speed for editing.

**Comment by vsch** [comment]
@tan9, fixed release updated. https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.8.4.zip

Thank you reporting this.

Pegdown is giving me tourette's. Next release will be without it.

**Comment by kangw3n** [comment]
Tested 1.8.4 and it works! Thanks
