### ISSUE TITLE
Argument for @NotNull parameter 'editorTextField' of 

### ISSUE THREAD

**Issue by mzbik** [vsch/idea-multimarkdown#280]
AppCode 2016.2
Build #OC-162.1236.19, built on July 19, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

One-time error. Tried to repo but I couldn't.

I was editing .md file, edit/preview displayed. Opened preferences, walked through viewing markdown-related items.  Closed preferences and received the following crash trace

Argument for @NotNull parameter 'editorTextField' of com/vladsch/idea/multimarkdown/settings/SettingsFormImpl.updateCustomizableTextFieldEditorEditable must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'editorTextField' of com/vladsch/idea/multimarkdown/settings/SettingsFormImpl.updateCustomizableTextFieldEditorEditable must not be null
    at com.vladsch.idea.multimarkdown.settings.SettingsFormImpl.updateCustomizableTextFieldEditorEditable(SettingsFormImpl.java)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettingsForm.updateFormOnReshow(MarkdownCssSettingsForm.java:257)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettingsForm$8.run(MarkdownCssSettingsForm.java:354)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vsch** [comment]
@mzbik, thanks for reporting it. It is initialization timing dependent. I will see if I can figure it out by analysis and code inspection. Some of these bugs are difficult to reproduce.
