### ISSUE TITLE
Not able to parse .md.erbfile

### ISSUE THREAD

**Issue by hallelujah** [vsch/idea-multimarkdown#285]
Hello,

### Versions

* Rubymine: 2016.2.1
* Markdown Navigator Plugin: 2.0.0
* OS: Mac OS X 10.11.6

Just to report something strange. It seems that the plugin is trying to parse `.erb` files prefixed by `.md`

My RubyMine settings

<img width="517" alt="preferences_and_baila_-____devel_rails_baila_" src="https://cloud.githubusercontent.com/assets/64276/17552185/a2d4e850-5efe-11e6-8c8a-4793ccf46741.png">

<img width="520" alt="preferences_and_baila_-____devel_rails_baila_" src="https://cloud.githubusercontent.com/assets/64276/17552250/2218f8b8-5eff-11e6-9186-cf8aaacf864c.png">

### File pages.md.erb

```
[home-page]: <%= root_path %>  "Account Edit"
[users-page]: <%= users_path %>  "Fields Definitions"
[admin-page]: <%= admin_path %> "Admin"
```

### Stacktrace

```
5
java.lang.ArrayIndexOutOfBoundsException: 5
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:129)
	at com.intellij.psi.templateLanguages.TemplateBlackAndWhiteLexer.a(TemplateBlackAndWhiteLexer.java:109)
	at com.intellij.psi.templateLanguages.TemplateBlackAndWhiteLexer.advance(TemplateBlackAndWhiteLexer.java:99)
	at com.intellij.lexer.MergingLexerAdapter$MyMergeFunction.merge(MergingLexerAdapter.java:45)
	at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:80)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:48)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.a(TemplateDataElementType.java:160)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:93)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:835)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:515)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:472)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:323)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.b(BreadcrumbsXmlWrapper.java:295)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:268)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:351)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.access$400(BreadcrumbsXmlWrapper.java:75)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper$MyUpdate.run(BreadcrumbsXmlWrapper.java:453)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2397)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.showNotify(MergingUpdateQueue.java:206)
	at com.intellij.util.ui.update.UiNotifyConnector.showNotify(UiNotifyConnector.java:82)
	at com.intellij.util.ui.update.UiNotifyConnector$1.run(UiNotifyConnector.java:60)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by vsch** [comment]
@hallelujah, thank you for the report. It seems that the IDE uses the double extension to specify the template language. 

The exception is caused by the IDE passing a lexer state to the markdown lexer that is outside the range. I added a test to ignore any lexer state that is outside legal range.

Patch release available from eap channel or direct download: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.6.zip>

It also has issues #285 and #287 fixed. 

You can download the patch release and install plugin from disk.

**Comment by hallelujah** [comment]
Thank you, tested and worked well!
