### ISSUE TITLE
IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#288]
Received an IndexOutOfBoundsException, Running IDEA 2106.2.2 and Markdown Navigator Version 2.0.0.

`
Index out of range: 1
java.lang.IndexOutOfBoundsException: Index out of range: 1
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:100)
	at com.vladsch.smart.SmartCharSequenceWrapper.get(SmartCharSequenceWrapper.kt:74)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl(SmartSegmentedCharSequence.kt:100)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl$SmartData(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.get(SmartCharSequenceBase.kt:68)
	at com.vladsch.smart.SmartSegmentedCharSequence.get(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.EditableCharSequence.get(EditableCharSequence.kt:46)
	at com.vladsch.smart.EditableCharSequence.charAt(EditableCharSequence.kt:26)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter$Companion.formatAtxHeader(MarkdownFormatter.kt:1000)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.AtxHeaderContext.adjustTrailingMarkers(AtxHeaderContext.kt:32)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.BackspaceHandler.charDeleted(BackspaceHandler.kt:189)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:109)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:348)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:437)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:340)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:331)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:88)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by aotte** [comment]
## Environment
Receiving the same type of error on Windows 10 in PyCharm 2016.2.1 with MDNavigator 2.0.0

## Reproduce Instructions
In a new MD file paste
| Syntax | Description                                                                   |
|:-------|:------------------------------------------------------------------------------|
| x + y  | Adds x and y                                                                  |
| x - y  | Subtracts y from x                                                            |
| x * y  | Multiplies x and y                                                            |
| x / y  | Divides x by y and always produces a float, or a complex if x or y is complex |

When pressing Enter at end of last table row, no new row gets created. When then manually adding the first pipe (|) the error occurs and keeps occurring if no other action is taken.

## Error details
update failed for AnAction with ID=com.vladsch.idea.multimarkdown.editor.actions.styling.DeleteRowAction: index 0 is not within range [0, 0)
java.lang.IndexOutOfBoundsException: index 0 is not within range [0, 0)
	at com.vladsch.smart.SmartCharSequenceBase.checkIndex(SmartCharSequenceBase.kt:325)
	at com.vladsch.smart.SmartCharSequenceWrapper.trackedSourceLocation(SmartCharSequenceWrapper.kt:91)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.nodeChars(ASTFlexmarkTableParser.kt:78)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:151)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:142)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:136)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:123)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:57)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.parseTable(ASTFlexmarkTableParser.kt:70)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser.parseTable(ASTFlexmarkTableParser.kt:44)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.parseMarkdownTable(TableContext.kt:78)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.access$parseMarkdownTable(TableContext.kt:34)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:58)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.getTable(TableContext.kt)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.canDeleteRow(TableContext.kt:96)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.DeleteRowAction.canPerformAction(DeleteRowAction.kt:22)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseTableAction.update(BaseTableAction.kt:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:123)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:96)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:942)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:65)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:174)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:634)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.r(FocusManagerImpl.java:615)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.m(FocusManagerImpl.java:585)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:481)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2397)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:461)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1417)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1407)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1391)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vsch** [comment]
@Javaru, thank you for the detailed report. I will make a patch release with a fix for this bug and post the download link here.

**Comment by SpencerBrown** [comment]
I'm seeing this frequently as well

here's the table I'm creating:


| `sslAllowInvalidHostnames` specified? | `--sslAllowInvalidCertificates` specified? | Server certificate validated | Server hostname checked |
|---------------------------------------|--------------------------------------------|------------------------------|-------------------------|
| No | No | | |
| No | Yes | | |
| Yes | No | | |
| Yes | Yes | | |

it crashes Markdown Navigator 2.0.0 with this backtrace:

```
update failed for AnAction with ID=com.vladsch.idea.multimarkdown.editor.actions.styling.DeleteRowAction: index 0 is not within range [0, 0)
java.lang.IndexOutOfBoundsException: index 0 is not within range [0, 0)
	at com.vladsch.smart.SmartCharSequenceBase.checkIndex(SmartCharSequenceBase.kt:325)
	at com.vladsch.smart.SmartCharSequenceWrapper.trackedSourceLocation(SmartCharSequenceWrapper.kt:91)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.nodeChars(ASTFlexmarkTableParser.kt:78)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:151)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:142)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:136)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visitChildren(ASTFlexmarkTableParser.kt:117)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.visit(ASTFlexmarkTableParser.kt:123)
	at com.vladsch.flexmark.internal.util.ast.VisitHandler.visit(VisitHandler.java:28)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:55)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visitChildren(NodeVisitor.java:47)
	at com.vladsch.flexmark.internal.util.ast.NodeVisitor.visit(NodeVisitor.java:57)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser$TableParsingVisitor.parseTable(ASTFlexmarkTableParser.kt:70)
	at com.vladsch.idea.multimarkdown.util.format.ASTFlexmarkTableParser.parseTable(ASTFlexmarkTableParser.kt:44)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.parseMarkdownTable(TableContext.kt:78)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.access$parseMarkdownTable(TableContext.kt:34)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:58)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext$table$2.invoke(TableContext.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.getTable(TableContext.kt)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.TableContext.canDeleteRow(TableContext.kt:96)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.DeleteRowAction.canPerformAction(DeleteRowAction.kt:22)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseTableAction.update(BaseTableAction.kt:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:123)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:96)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:942)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:65)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:174)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:634)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.m(FocusManagerImpl.java:615)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:585)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:481)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2397)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:461)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1417)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1407)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1391)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@SpencerBrown, the bug you are seeing I think is addressed by a previous patch. You can get the latest from the EAP channel for the plugin or direct download: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.8.zip

Please let me know if the latest patch does or does not address your issue.

**Comment by SpencerBrown** [comment]
@vsch Yes, version 2.0.0.8 fixes my issue! Thanks. I'm glad I'm a paid subscriber, this plugin is the best I've seen and I use it daily.

**Comment by vsch** [comment]
@SpencerBrown, thank you for the encouraging feedback. The nature of issues means I mostly get bugs and complaints. Positive feedback helps balance the user perception of the plugin. 👍
