### ISSUE TITLE
IndexOutOfBoundsException: Index out of range: 190

### ISSUE THREAD

**Issue by truckingsim** [vsch/idea-multimarkdown#302]
I'm on version 2.1.0 got this right after typing a header and right before selecting text at the end of a file.    Not sure which one caused it. 

Here's the stacktrace:

```
Index out of range: 190
java.lang.IndexOutOfBoundsException: Index out of range: 190
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:100)
	at com.vladsch.smart.SmartCharSequenceWrapper.get(SmartCharSequenceWrapper.kt:74)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl(SmartSegmentedCharSequence.kt:100)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl$SmartData(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.get(SmartCharSequenceBase.kt:68)
	at com.vladsch.smart.SmartSegmentedCharSequence.get(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.EditableCharSequence.get(EditableCharSequence.kt:46)
	at com.vladsch.smart.EditableCharSequence.charAt(EditableCharSequence.kt:26)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter$Companion.formatAtxHeader(MarkdownFormatter.kt:1017)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.AtxHeaderContext.adjustTrailingMarkers(AtxHeaderContext.kt:32)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.BackspaceHandler.charDeleted(BackspaceHandler.kt:189)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:109)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:348)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:437)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:340)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:331)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:88)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:607)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Everything seems to still be working after that error.  Love the plugin thanks for everything you do!

**Comment by truckingsim** [comment]
Happened again here's the stacktrace from the second time:

```
Index out of range: 930
java.lang.IndexOutOfBoundsException: Index out of range: 930
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:100)
	at com.vladsch.smart.SmartCharSequenceWrapper.get(SmartCharSequenceWrapper.kt:74)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl(SmartSegmentedCharSequence.kt:100)
	at com.vladsch.smart.SmartSegmentedCharSequence.charAtImpl$SmartData(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.get(SmartCharSequenceBase.kt:68)
	at com.vladsch.smart.SmartSegmentedCharSequence.get(SmartSegmentedCharSequence.kt:26)
	at com.vladsch.smart.SmartCharSequenceBase.charAt(SmartCharSequenceBase.kt:26)
	at com.vladsch.smart.EditableCharSequence.get(EditableCharSequence.kt:46)
	at com.vladsch.smart.EditableCharSequence.charAt(EditableCharSequence.kt:26)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter$Companion.formatAtxHeader(MarkdownFormatter.kt:1017)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.AtxHeaderContext.adjustTrailingMarkers(AtxHeaderContext.kt:32)
	at com.vladsch.idea.multimarkdown.editor.actions.handlers.BackspaceHandler.charDeleted(BackspaceHandler.kt:189)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:109)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:348)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:437)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:340)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:331)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:88)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:607)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@truckingsim, thank you for the report. I will post a link here to a patch release that addresses the issue.

**Comment by vsch** [comment]
@truckingsim, I was able to identify the issue.

It occurs when an ATX header marker occurs at the end of the document without any following characters.

1. Format document will cause another index out of bounds exception
2. Backspace that removes the last character after the ATX marker at the end of the file will cause this exact exception.

I will make a patch release to address this issue soon.

**Comment by truckingsim** [comment]
@vsch that makes a lot of sense and falls inline with what I was doing when the error's happened.  Thanks for the quick find!

**Comment by vsch** [comment]
@truckingsim, Fixed in EAP update channel or download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.0.4.zip
