### ISSUE TITLE
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize

### ISSUE THREAD

**Issue by clxhhsy** [vsch/idea-multimarkdown#312]
```
Plugin Error: Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.
java.lang.ClassNotFoundException: com.vladsch.idea.multimarkdown.MultiMarkdownPlugin
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:214)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:384)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

how to fix it?thx

**Comment by vsch** [comment]
@clxhhsy, the error shows that the main class of the plugin cannot be found. It seems that there is something wrong with the plugin installation.

You should delete the plugin directory for the IDE product and re-install the plugin. This is OS and product dependent.

On OS X for IDEA Community it is in the `~/Library/Application Support/IdealC2016.2/idea-multimarkdown`

What IDE product and what OS are you using?

**Comment by clxhhsy** [comment]
@vsch, the error happened when i was debugging the source code ,not install plugin . my IDE :idea 2016.2.4  and my OS :win10

**Comment by vsch** [comment]
@clxhhsy, it seems that the build and debug is not updating the sandbox home directory with the built plugin for IDE under debug.

Here is what I use, can you check to see if the sandbox directory you have configured in the SDK you are using does have the plugin classes:

<img width="1263" alt="screen shot 2016-10-12 at 4 16 06 pm" src="https://cloud.githubusercontent.com/assets/10299086/19326233/ad696514-9097-11e6-8f4e-33418f246744.png">

<img width="600" alt="screen shot 2016-10-12 at 4 18 22 pm" src="https://cloud.githubusercontent.com/assets/10299086/19326237/b0bf4a9e-9097-11e6-957b-ecbe2e515c99.png">

**Comment by clxhhsy** [comment]
@vsch ,yeah ,i have fixed it! thx!
