### ISSUE TITLE
Assertion when adding/removing a line

### ISSUE THREAD

**Issue by Kendos-Kenlen** [vsch/idea-multimarkdown#33]
The following assertion appear when I create or remove a line :

```java
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:153)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:114)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.a(JavaPsiFacadeImpl.java:124)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:98)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:96)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:949)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveClassReference(MultiMarkdownPathResolver.java:96)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$2.run(MultiMarkdownPathResolver.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveLink(MultiMarkdownPathResolver.java:180)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.canResolveLink(MultiMarkdownPathResolver.java:110)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.checkTarget(MultiMarkdownLinkRenderer.java:66)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:82)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:134)
	at org.pegdown.ast.ExpLinkNode.accept(ExpLinkNode.java:33)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:381)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:418)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:425)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:190)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:89)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:70)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.markdownToHtml(MultiMarkdownPreviewEditor.java:471)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.updateHtmlContent(MultiMarkdownPreviewEditor.java:492)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.access$100(MultiMarkdownPreviewEditor.java:74)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor$5$1.run(MultiMarkdownPreviewEditor.java:401)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:153)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:114)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.a(JavaPsiFacadeImpl.java:124)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:98)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:96)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:949)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveClassReference(MultiMarkdownPathResolver.java:96)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$2.run(MultiMarkdownPathResolver.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveLink(MultiMarkdownPathResolver.java:180)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.canResolveLink(MultiMarkdownPathResolver.java:110)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.checkTarget(MultiMarkdownLinkRenderer.java:66)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:82)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:134)
	at org.pegdown.ast.ExpLinkNode.accept(ExpLinkNode.java:33)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:381)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:418)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:425)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:190)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:89)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:70)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.markdownToHtml(MultiMarkdownPreviewEditor.java:471)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.updateHtmlContent(MultiMarkdownPreviewEditor.java:492)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.access$100(MultiMarkdownPreviewEditor.java:74)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor$5$1.run(MultiMarkdownPreviewEditor.java:401)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:153)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:114)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.a(JavaPsiFacadeImpl.java:124)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:98)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$1.compute(MultiMarkdownPathResolver.java:96)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:949)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveClassReference(MultiMarkdownPathResolver.java:96)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver$2.run(MultiMarkdownPathResolver.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.resolveLink(MultiMarkdownPathResolver.java:180)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPathResolver.canResolveLink(MultiMarkdownPathResolver.java:110)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.checkTarget(MultiMarkdownLinkRenderer.java:66)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.render(MultiMarkdownLinkRenderer.java:82)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:134)
	at org.pegdown.ast.ExpLinkNode.accept(ExpLinkNode.java:33)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:381)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:418)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:425)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:190)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildrenSkipFirst(MultiMarkdownToHtmlSerializer.java:188)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownToHtmlSerializer.visitChildren(MultiMarkdownToHtmlSerializer.java:113)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:89)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:70)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.markdownToHtml(MultiMarkdownPreviewEditor.java:471)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.updateHtmlContent(MultiMarkdownPreviewEditor.java:492)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor.access$100(MultiMarkdownPreviewEditor.java:74)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownPreviewEditor$5$1.run(MultiMarkdownPreviewEditor.java:401)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I use the last JDK + the last EAP of IDEA and the last version of the plugin on Linux.

**Comment by vsch** [comment]
Thank you for the report. I will double check but I think this is already fixed in the next release. I will let you know if when you can download a fixed interim release from the GitHub repository.

**Comment by vsch** [comment]
@Kendos-Kenlen, New build available in this repo under dist or from the JetBrains Plugin Page or Repository.

**Comment by Kendos-Kenlen** [comment]
Thank you, I'll update it and tell you if the problem is still present.
