### ISSUE TITLE
Cannot init ProjectCodeStyleSettingsManager component state: java.lang.AssertionError: Unexpected content storage modification

### ISSUE THREAD

**Issue by tysonite** [vsch/idea-multimarkdown#333]
Got exception while opening project in the IDEA (Community edition):
Idea version:
IntelliJ IDEA 2016.2.5
Build #IC-162.2228.15, built on October 14, 2016
JRE: 1.8.0_112-release-287-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

```
Cannot init ProjectCodeStyleSettingsManager component state: java.lang.AssertionError: Unexpected content storage modification
java.lang.RuntimeException: java.lang.AssertionError: Unexpected content storage modification
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:544)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:164)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeContent(FSRecords.java:1581)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.writeContent(PersistentFSImpl.java:233)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:507)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:127)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:119)
	at com.intellij.configurationStore.FileBasedStorage.loadLocalData(FileBasedStorage.kt:121)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:62)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:31)
	at com.intellij.openapi.components.impl.stores.StateStorageBase.getStorageData(StateStorageBase.kt:57)
	at com.intellij.configurationStore.StorageBaseEx.createGetSession(StorageBaseEx.kt:25)
	at com.intellij.configurationStore.StorageBaseEx.createGetSession$default(StorageBaseEx.kt:25)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistentComponent(ComponentStoreImpl.kt:284)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:44)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getSettings(CodeStyleSettingsManager.java:70)
	at com.vladsch.idea.multimarkdown.language.codeStyle.MarkdownNavigatorCodeStyleSettings.migrateSettings(MarkdownNavigatorCodeStyleSettings.java:115)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$projectOpened$5.run(MultiMarkdownProjectComponent.kt:450)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:882)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:562)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:192)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:116)
	at com.intellij.ide.actions.OpenFileAction.doOpenFile(OpenFileAction.java:85)
	at com.intellij.ide.actions.OpenFileAction.lambda$actionPerformed$0(OpenFileAction.java:66)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:163)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:111)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:89)
	at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:58)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:66)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:145)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:79)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:328)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:627)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.AssertionError: Unexpected content storage modification
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findOrCreateContentRecord(FSRecords.java:1748)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$2400(FSRecords.java:62)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.writeBytes(FSRecords.java:1657)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeContent(FSRecords.java:1579)
	... 91 more
```

**Comment by vsch** [comment]
@tysonite, thank you for the report. I am looking into what is causing it.

**Comment by tysonite** [comment]
@vsch, thanks. Either bug in Idea or plugin. Just after that exception Idea cleared its configuration in the user's home directory saying that it is corrupted.
