### ISSUE TITLE
Exception while opening markdown file in Android Studio

### ISSUE THREAD

**Issue by emartynov** [vsch/idea-multimarkdown#334]
Here is exception from logs:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanelProvider.createHtmlPanel(JavaFxHtmlPanelProvider.kt:77)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$setUpPanel$1.run(PreviewFileEditorBase.kt:281)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: com/vladsch/idea/multimarkdown/editor/javafx/JFXPanelWrapper
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel.<init>(JavaFxHtmlPanel.kt:340)
```

**Comment by vsch** [comment]
@emartynov this should happen only the first time you open a markdown file when the plugin is first installed or detects JRE version change. The plugin tries to create a JavaFX WebView based browser. If it fails it defaults to Swing browser and sets a config flag not to try until JRE version change.

Does this description make sense in your observed behaviour?

**Comment by emartynov** [comment]
It happens whenever I open markdown file. I see this error constantly.

**Comment by vsch** [comment]
@emartynov, the plugin tries to detect if JavaFX WebView is available and if not then it will not even try to make it as an option. Can you select Swing preview browser at least until i can see if I can duplicate this.

❓ What OS and JVM version are you running Android studio on?

To disable attempts at using JavaFX select Swing as the preview browser from:

![screenshot_settings_previewbrowser](https://cloud.githubusercontent.com/assets/10299086/20220810/f91cf328-a7fc-11e6-82fd-948bca92255b.png)

**Comment by vsch** [comment]
@emartynov, I found a possible cause. A class added to the JavaFX preview browser was not added to the custom class loader. This should not be a problem since the custom class loader is only needed for older versions of the IDE using an Open JDK version that is missing JavaFX support files.

I will be making another EAP plugin release with this fix in it. I will post a link to the distribution zip here once it is available.

**Comment by emartynov** [comment]
Thanks! If you still need my environment details:

- MacOS Sierra 10.12.1
- Android Studio 2.3 Canary
- JRE: 1.8.0_112-release-b05 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by emartynov** [comment]
I've changed settings and don't see this error anymore!

**Comment by vsch** [comment]
@emartynov, it is a temporary solution because your preview is Swing, which has a minimal set of features. It is much faster than WebView.

I would like to see if the possible cause I found was the reason. I will let you as soon as I have the new EAP release ready.
