### ISSUE TITLE
PhpStorm 9.5 EAP crashes when MultiMarkdown installed

### ISSUE THREAD

**Issue by nazar-pc** [vsch/idea-multimarkdown#35]
Current build is PS-142.4912

**Comment by vsch** [comment]
I am working on a new build that has more robust checks during file scanning, startup and link resolution. I should have it ready in a day or two. Sorry about the crash. I am still absorbing the complexity of IDEA environment and all the differences in end user configurations that can arise.

**Comment by nazar-pc** [comment]
Thanks, I'll wait

**Comment by vsch** [comment]
@nazar-pc, New build available in this repo under dist or from the JetBrains Plugin Page or Repository.

**Comment by nazar-pc** [comment]
With 1.1.11 still crashes:
```
nazar-pc@nazar-pc ~/P/bin> ./phpstorm.sh 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
[YourKit Java Profiler 2014 build 14112] Log file: /home/nazar-pc/.yjp/log/WebIde95-10096.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INFO com.vladsch.idea.multimarkdown  - JavaFX library jfxrt.jar found in /home/nazar-pc/PhpStorm/jre/jre/lib the current jre: /home/nazar-pc/PhpStorm/jre/jre, version 1.8.0_60
INFO com.vladsch.idea.multimarkdown  - creating temp font file: /home/nazar-pc/.WebIde95/system/tmp/multimarkdown_taskitems.ttf
[  43292]  ERROR - ellij.project.impl.ProjectImpl - com.github.mfedko.idea.plugins.filelanguage.FileLanguageProjectComponent@4ee5c64c 
java.lang.NoSuchFieldError: INSTANCE
	at com.github.mfedko.idea.plugins.filelanguage.FileLanguagePanel.<init>(FileLanguagePanel.java:70)
	at com.github.mfedko.idea.plugins.filelanguage.FileLanguageProjectComponent.projectOpened(FileLanguageProjectComponent.java:23)
	at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:393)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:63)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:427)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:718)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:355)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:222)
	at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:56)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:61)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:124)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:350)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[  43293]  ERROR - ellij.project.impl.ProjectImpl - PhpStorm PS-142.4912  Build #PS-142.4912 
[  43294]  ERROR - ellij.project.impl.ProjectImpl - JDK: 1.8.0_60 
[  43294]  ERROR - ellij.project.impl.ProjectImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  43294]  ERROR - ellij.project.impl.ProjectImpl - Vendor: Oracle Corporation 
[  43294]  ERROR - ellij.project.impl.ProjectImpl - OS: Linux 
[  43294]  ERROR - ellij.project.impl.ProjectImpl - Last Action:  
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6823f0699d, pid=10096, tid=140081402144512
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x8a999d]  Method::build_method_counters(Method*, Thread*)+0x2d
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/nazar-pc/java_error_in_WEBIDE_10096.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by vsch** [comment]
@nazar-pc, it is not crashing in idea-multimarkdown but in mfedko/idea-plugins-filelanguage.

I'll install that plugin tomorrow and see what is going on. Today is already 1:00 am here in Montreal and I am overdue for some rest.  I'll let you know what I find.
