### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by rquadling** [vsch/idea-multimarkdown#38]
null
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Having too many issues with this plugin now :-(. So uninstalling.

**Comment by vsch** [comment]
@rquadling, thanks for the report. I have it fixed for the next release. I will let you know when a new version is ready for download.

**Comment by vsch** [comment]
@rquadling, new release is available. Has this bug fixed but I would like to know if it fixes it on your system.

**Comment by rquadling** [comment]
Thank you.
