### ISSUE TITLE
Null Pointer Exception on 

### ISSUE THREAD

**Issue by mt3o** [vsch/idea-multimarkdown#389]
Error happened just after starting IntelliJ 2016.3.2. Linux, Ubuntu

Can I do something with this or just disable the plugin for a while?

java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.util.DelimitedBuilder.append(DelimitedBuilder.java:149)
	at com.vladsch.idea.multimarkdown.editor.actions.DisabledConditionBuilder.<init>(DisabledConditionBuilder.java:56)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.ToggleAutoFormatTableAction.update(ToggleAutoFormatTableAction.kt:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:267)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:510)
	at com.intellij.ide.util.gotoByName.GotoActionModel.a(GotoActionModel.java:430)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vsch** [comment]
@mt3o, you can temporarily disable the plugin but I will be making an EAP release in a few minutes to address this bug. I will post instructions here for the updated distribution zip.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
