### ISSUE TITLE
"Invalid file" Exception when network drive disappears

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#410]
I got this exception upon IJ frame activation when a network drive got lost meanwhile.
```
Invalid file: file:///Volumes/some/server/path/my_file.md
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:401)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:182)
	at com.vladsch.idea.multimarkdown.settings.profile.RenderingProfileManager.getRenderingProfile(RenderingProfileManager.java:317)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction$update$conditionBuilder$1$1.run(BaseToggleStateAction.kt:138)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction$update$conditionBuilder$1$1.run(BaseToggleStateAction.kt:48)
	at com.vladsch.idea.multimarkdown.editor.actions.DisabledConditionBuilder.notNull(DisabledConditionBuilder.java:79)
	at com.vladsch.idea.multimarkdown.editor.actions.DisabledConditionBuilder.notNull(DisabledConditionBuilder.java:130)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction$update$conditionBuilder$1.run(BaseToggleStateAction.kt:137)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction$update$conditionBuilder$1.run(BaseToggleStateAction.kt:48)
	at com.vladsch.idea.multimarkdown.editor.actions.DisabledConditionBuilder.and(DisabledConditionBuilder.java:185)
	at com.vladsch.idea.multimarkdown.editor.actions.styling.BaseToggleStateAction.update(BaseToggleStateAction.kt:135)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:96)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:942)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:65)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:174)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:649)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.h(FocusManagerImpl.java:630)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.m(FocusManagerImpl.java:600)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:106)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2493)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Not a big deal for me, but having a plugin being blamed by IJ for throwing an uncaught exception does not make a good impression to some endusers I guess.

**Comment by vsch** [comment]
@holgerbrandl, there are many instances when a plugin is blamed for IJ internal state changes.

Trying to catch all possibilities in the plugin code is hopeless.

In this case there is a virtual file associated with an editor document. The network drive goes away and the file is now marked invalid. When this virtual file is passed to a JetBrains API call an exception is thrown that it is not valid.

I will add a test in this case but I am sure similar code needs to be peppered throughout the code. Virtual file is a basic element of identifying what is being modified.

What does IJ do when you try to save the file? What would be the correct action for the plugin to handle sudden invalidation of an editor virtual file?

**Comment by vsch** [comment]
@holgerbrandl, the virtual file is obtained from `FileDocumentManager.getInstance().getFile(editor!!.document)` call in which case the IDE should probably return null instead of returning an invalid virtual file.

I'll add a test but this seems like a kludge.

**Comment by holgerbrandl** [comment]
As said before, it's not bothering me in any way, I just wanted to share it with you.

**Comment by vsch** [comment]
@holgerbrandl, please keep letting me know. I will address as many and as fast I can. I was just pointing out that chances of me catching all cases where this type of network drop out would be addressed is slim to none. 

In this case I removed the virtual file reference and using the PsiFile which has its own virtual file. Hoping that this will allow the IDE to handle it better, although no guarantee.
