### ISSUE TITLE
Exception when starting IDEA

### ISSUE THREAD

**Issue by leventov** [vsch/idea-multimarkdown#414]
```
Already disposed
java.lang.AssertionError: Already disposed
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.java:138)
	at com.vladsch.idea.multimarkdown.settings.MarkdownProjectSettings.notifyOnSettingsChanged(MarkdownProjectSettings.kt:250)
	at com.vladsch.idea.multimarkdown.settings.MarkdownProjectSettings.access$notifyOnSettingsChanged(MarkdownProjectSettings.kt:32)
	at com.vladsch.idea.multimarkdown.settings.MarkdownProjectSettings$1.run(MarkdownProjectSettings.kt:71)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@leventov, thank you for reporting this. It occurs when there is a delayed action in a project and the project is closed before the action is triggered.

It is fixed for next release. For now you can safely ignore this error.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
