### ISSUE TITLE
NPE version 2.3.4 (w/license)

### ISSUE THREAD

**Issue by SpencerBrown** [vsch/idea-multimarkdown#416]
I typed:

```
* *something*
```
 and got NPE:

```
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownIndentingCompositeImpl$Companion.actualTextPrefix(MultiMarkdownIndentingCompositeImpl.kt:187)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownIndentingCompositeImpl.actualTextPrefix(MultiMarkdownIndentingCompositeImpl.kt:250)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter$Companion.listItemNeedsSpaceAfterMarker(MarkdownFormatter.kt:1130)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter.listItemNeedsSpaceAfterMarker(MarkdownFormatter.kt)
	at com.vladsch.idea.multimarkdown.annotator.MultiMarkdownAnnotator.annotateList(MultiMarkdownAnnotator.java:289)
	at com.vladsch.idea.multimarkdown.annotator.MultiMarkdownAnnotator.annotate(MultiMarkdownAnnotator.java:132)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by vsch** [comment]
@SpencerBrown, thank you for reporting it.

It appears from the stack trace that it is a timing issue between typing and the parse tree. The list item has no children even though this is not possible because it has to have at least the list item marker node as the first child.

I added a test for this so it does not cause an exception if this occurs. For now ignore it if it occurs again.
