### ISSUE TITLE
java.lang.IllegalStateException: node.treeNext must not be null

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#420]
I got the following exception in IntelliJ IDEA v2017.1 (build 171.2780.107) with Markdown Navigator 2.3.4.30. Unfortunately I am not sure what action specifically triggered the exception as I did not notice it immediately.

```
In file: file://P:/dev/proj/foo/README.md: node.treeNext must not be null
java.lang.IllegalStateException: node.treeNext must not be null
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownIndentingCompositeImpl$Companion.actualTextPrefix(MultiMarkdownIndentingCompositeImpl.kt:197)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownIndentingCompositeImpl.actualTextPrefix(MultiMarkdownIndentingCompositeImpl.kt:250)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter$Companion.listItemNeedsSpaceAfterMarker(MarkdownFormatter.kt:1145)
	at com.vladsch.idea.multimarkdown.util.format.MarkdownFormatter.listItemNeedsSpaceAfterMarker(MarkdownFormatter.kt)
	at com.vladsch.idea.multimarkdown.annotator.MultiMarkdownAnnotator.annotateList(MultiMarkdownAnnotator.java:265)
	at com.vladsch.idea.multimarkdown.annotator.MultiMarkdownAnnotator.annotate(MultiMarkdownAnnotator.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by vsch** [comment]
@Javaru, thank you for the report. It is an error that would depend on the markdown contents. Most likely you got it while typing.  I fixed it for next release. Too much reliance on compile time kotlin null warnings.

I will make an EAP release tomorrow with the fix.
