### ISSUE TITLE
PHPStorm - IDE Fatal Error

### ISSUE THREAD

**Issue by nirfrank** [vsch/idea-multimarkdown#44]
Hello,

I have multimarkdown installed on PHPStorm 9.0.2. Today, while opening up the IDE, I was greeted with an IDE fatal error. Here are the details from the crash report:
```
@NotNull method com/vladsch/idea/multimarkdown/util/ThreadSafeMirrorCache.getCache must not return null

java.lang.IllegalStateException: @NotNull method com/vladsch/idea/multimarkdown/util/ThreadSafeMirrorCache.getCache must not return null
	at com.vladsch.idea.multimarkdown.util.ThreadSafeMirrorCache.getCache(ThreadSafeMirrorCache.java:30)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:167)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bbrala** [comment]
Had the same yesterday i think, but only happened once.

**Comment by vsch** [comment]
Please try the latest version 1.1.12. This is a bug in version 1.1.11 which is timing sensitive during initialization and shows up intermittently. Version 1.1.12 has it fixed.
