### ISSUE TITLE
Failed processing Markdown document: Error while parsing action

### ISSUE THREAD

**Issue by bbrala** [vsch/idea-multimarkdown#46]
Threw away cache and reloaded.

# Error message
```
Failed processing Markdown document: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Table/Sequence/Optional/Sequence/NodeSequence/Sequence/TableRow/Sequence/OneOrMore/Sequence/TableCell/NodeSequence/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 503, pos 1):
```

# Details
```
Failed processing Markdown document: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Table/Sequence/Optional/Sequence/NodeSequence/Sequence/TableRow/Sequence/OneOrMore/Sequence/TableCell/NodeSequence/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 503, pos 1):
**strRightBack**  _.strRightBack(string, pattern)
^

org.pegdown.ParsingTimeoutException
org.parboiled.errors.ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Table/Sequence/Optional/Sequence/NodeSequence/Sequence/TableRow/Sequence/OneOrMore/Sequence/TableCell/NodeSequence/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 503, pos 1):
**strRightBack**  _.strRightBack(string, pattern)
^

org.pegdown.ParsingTimeoutException
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:366)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.matchers.MemoMismatchesMatcher.match(MemoMismatchesMatcher.java:41)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.OneOrMoreMatcher.match(OneOrMoreMatcher.java:38)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.OneOrMoreMatcher.match(OneOrMoreMatcher.java:38)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.matchers.VarFramingMatcher.match(VarFramingMatcher.java:44)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.OptionalMatcher.match(OptionalMatcher.java:36)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.matchers.VarFramingMatcher.match(VarFramingMatcher.java:44)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.FirstOfMatcher.match(FirstOfMatcher.java:41)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.ZeroOrMoreMatcher.match(ZeroOrMoreMatcher.java:39)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.matchers.SequenceMatcher.match(SequenceMatcher.java:46)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	at org.parboiled.parserunners.BasicParseRunner.run(BasicParseRunner.java:72)
	at org.parboiled.parserunners.ReportingParseRunner.runBasicMatch(ReportingParseRunner.java:86)
	at org.parboiled.parserunners.ReportingParseRunner.run(ReportingParseRunner.java:66)
	at org.parboiled.parserunners.AbstractParseRunner.run(AbstractParseRunner.java:81)
	at org.pegdown.Parser.parseToParsingResult(Parser.java:1787)
	at org.pegdown.Parser.parseInternal(Parser.java:1774)
	at org.pegdown.Parser.parse(Parser.java:91)
	at org.pegdown.PegDownProcessor.parseMarkdown(PegDownProcessor.java:181)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParser.parseMarkdown(MultiMarkdownLexParser.java:282)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:83)
	at com.intellij.lexer.DelegateLexer.start(DelegateLexer.java:39)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexer.start(BaseFilterLexer.java:153)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.psi.impl.cache.impl.BaseFilterLexerUtil.scanContent(BaseFilterLexerUtil.java:48)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:36)
	at com.intellij.psi.impl.cache.impl.todo.LexerBasedTodoIndexer.map(LexerBasedTodoIndexer.java:32)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: org.pegdown.ParsingTimeoutException
	at org.pegdown.Parser.checkForParsingTimeout(Parser.java:1792)
	at org.pegdown.Action$cxzDYiA1YTOH9nKV.run(Unknown Source)
	at org.parboiled.matchers.ActionMatcher.match(ActionMatcher.java:96)
	at org.parboiled.parserunners.BasicParseRunner.match(BasicParseRunner.java:77)
	at org.parboiled.MatcherContext.runMatcher(MatcherContext.java:351)
	... 110 more

```

**Comment by vsch** [comment]
The pegdown parser is iterative and can take too long trying to process markdown. This will happen on large blocks of text with unmatched inline markdown markers. The known suspects for this is the Quotes extension. If you have it enabled, try disabling it and see if the document will parse. I am even considering removing it as an option because of its tendency to timeout.

If the document that causes this is not proprietary, can you make it available to me for testing? I have been wanting to see if I can modify the pegdown parser so that it is faster in giving up trying to parse something that it cannot.

**Comment by bbrala** [comment]
I've uploaded all MD files in the project that failed to wetransfer. It pretty much node and php stuff. But only libraries of others.

http://we.tl/ouqXSJPkDY

**Comment by vsch** [comment]
Thanks. I am looking into it now.

**Comment by bbrala** [comment]
It was only once tho, reloaded cache a few times after that without a problem. So i hope you can find the bug :)

**Comment by bbrala** [comment]
I've didn't have it later tho, so be carefull, maybe it was related to the .11 bug with the timing or something?

**Comment by vsch** [comment]
I hope you don't have all these directories marked as Sources Root. There are over 3800 markdown files there.

If the file is in a source root (not library source root) then the plugin will consider the file for link resolution annotations and completions. It will be slow to search through the list to pick out candidate files from very large lists. Unless you are making links to these files or actively working on them then there is no need to have them as source. Any file can be viewed, regardless of its source status.

I tried both enabling the directory as source root with all 3826 markdown files and it took a while for the idea to index everything and response time was the pits but nothing died. When I unmarked the directory as a source root everything looked good.

I suspect that it was a version 1.1.11 issue. There were a few things off in the indexing, since it was an early implementation. I still have to optimize handling of large file sets. I am not cacheing enough and clearing the cache unnecessarily but in the early stages of parser development I want to avoid stale cache issues more than slow performance.

Thank you for this mega load of markdown files. I'll use them for optimization testing. :+1:
