### ISSUE TITLE
PHPStorm - IDE Fatal Error (Already disposed: Project (Disposed) mycheck-docs

### ISSUE THREAD

**Issue by nirfrank** [vsch/idea-multimarkdown#47]
PHPStorm version 9.0.2
Multimarkdown version 1.1.12

Step 1-
Closed an open project (mycheck-docs) after saving, committing, and pushing.

Step 2-
Without closing PHPStorm, opened a new, unrelated project.

Step 3-
Upon opening of the project, was greeted with the following IDE fatal error:

```
Already disposed: Project (Disposed) mycheck-docs
java.lang.AssertionError: Already disposed: Project (Disposed) mycheck-docs
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:192)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:35)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditor.isMyTabSelected(MultiMarkdownFxPreviewEditor.java:663)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownFxPreviewEditor$10$1.run(MultiMarkdownFxPreviewEditor.java:655)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@nirfrank, thank you for bringing it to my attention. I fixed it for next release.

You can ignore the error in the current release. It happens if the markdown source is modified but the project is closed before the preview is updated. The update delay timer thread triggers after the project is already closed. IDEA catches the error and generates a log entry. Everything continues to work, since it affects only orphaned threads that should have exited early, it has no impact on operation.
