### ISSUE TITLE
Error when starting `Cannot find element among its parent' children.`

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#536]
```
Cannot find element among its parent' children. element: 'PsiDirectory:xxx/blog'; parent: 'PsiDirectory:xxx'; children: [PsiDirectory:xxx/blog, PsiDirectory:xxx/halp, PsiDirectory:xxx/.idea, PsiDirectory:xxx/notes, PsiDirectory:xxx/style, PsiDirectory:xxx/hammerspoon, PsiDirectory:xxx/gdrive-xxx-vjpr-notes, PsiDirectory:xxx/gdrive-xxx-platform-notes];  file:null
java.lang.Throwable: Cannot find element among its parent' children. element: 'PsiDirectory:xxx/blog'; parent: 'PsiDirectory:xxx'; children: [PsiDirectory:xxx/blog, PsiDirectory:xxx/halp, PsiDirectory:xxx/.idea, PsiDirectory:xxx/notes, PsiDirectory:xxx/style, PsiDirectory:xxx/hammerspoon, PsiDirectory:xxx/gdrive-xxx-vjpr-notes, PsiDirectory:xxx/gdrive-xxx-platform-notes];  file:null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:136)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:124)
	at com.intellij.psi.impl.PsiElementBase.getPrevSibling(PsiElementBase.java:62)
	at com.vladsch.idea.multimarkdown.language.breadcrumbs.MarkdownBreadcrumbsInfoProvider.getSiblingHeading(MarkdownBreadcrumbsInfoProvider.java:216)
	at com.vladsch.idea.multimarkdown.language.breadcrumbs.MarkdownBreadcrumbsInfoProvider.getParentRaw(MarkdownBreadcrumbsInfoProvider.java:178)
	at com.vladsch.idea.multimarkdown.language.breadcrumbs.MarkdownBreadcrumbsInfoProvider.getParent(MarkdownBreadcrumbsInfoProvider.java:159)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.b(BreadcrumbsXmlWrapper.java:370)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:321)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:281)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:409)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:225)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.access$400(BreadcrumbsXmlWrapper.java:82)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper$MyUpdate.run(BreadcrumbsXmlWrapper.java:513)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2781)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
@vjpr, I got the exception report and think I fixed the issue but since I cannot duplicate it cannot be sure. I made and EAP release with the fix but if you have a markdown file that causes this I would appreciate if you can provide it so I can duplicate the issue and be sure of what causes this.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vjpr** [comment]
Thanks! It's fixed.
