### ISSUE TITLE
IDE fatal error regularly occurring in Idea 2018.1 EAP

### ISSUE THREAD

**Issue by bmcclure** [vsch/idea-multimarkdown#559]
Since updating to the new IDEA Ultimate 2018.1 EAP when it was released a week or two ago, I regularly get this exception occurring:

```
2 intention duplicates found for com.vladsch.idea.multimarkdown.intentions.flexmark.ToggleFlexmarkExampleIgnoreIntention@15c0a31a]
java.lang.IllegalStateException: [2 intention duplicates found for com.vladsch.idea.multimarkdown.intentions.flexmark.ToggleFlexmarkExampleIgnoreIntention@15c0a31a]
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.checkForDuplicates(IntentionManagerImpl.java:300)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:275)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:337)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:245)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

It shows up as a core IDE bug so it only lets me submit it to JetBrains, but I'm pretty sure it's gotta be related to Markdown Navigator.

This occurs in both Windows 10 and Elementary OS on the latest EAP release (I update daily as new releases are available, and the issue has been consistent since the first 2018.1 EAP release through the latest one).

**Comment by bmcclure** [comment]
Just to confirm (not that it matters in this case most likely), I have the core Markdown Support plugin disabled, so Markdown Navigator is my only Markdown-related plugin that I'm aware of.

**Comment by vsch** [comment]
@bmcclure, yes it is a plugin bug. It was fixed in the last EAP. It is an unused intention and previous versions of the IDE ignored it.

Please update to 2.4.0.42, I had the bug fixed since I started using 2018.1 EAP. 

I usually run the plugin from a build of the master branch of intellij-community but 2018 has a few annoying bugs that kept me from switching to it until I finally decided to live with the bugs until they get fixed and uncovered a few issues.

**Comment by bmcclure** [comment]
Ah, wow, I actually had never noticed the select box to switch to an EAP release of Markdown Navigator. I didn't even know that it was possible for plugins to have different release channels. Thanks for pointing that out!

**Comment by vsch** [comment]
@bmcclure, actually JetBrains plugin site has the channels implemented now. I don't use it because when I implemented mine they did not have it working. Now that I have my own, I don't bother switching over. Too many things to do and not enough time, especially to fiddle with what works.

**Comment by bdonkey** [comment]
Where do I find the EAP release? I've looked the [product](http://vladsch.com/product/markdown-navigator) site and at the [plugin](https://plugins.jetbrains.com/plugin/7896-markdown-navigator) site, but do not see any EAP channel option.

**Comment by vsch** [comment]
@bdonkey, sorry forgot to include the customary instructions:

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by bdonkey** [comment]
got it…thank you..scott
