### ISSUE TITLE
2.5.0 crashing on initialization

### ISSUE THREAD

**Issue by SpencerBrown** [vsch/idea-multimarkdown#570]
updated this morning. Version: 2.5.0. WebStorm 2017.3.5

```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NoSuchMethodError: com.intellij.ui.JBColor.link()Ljava/awt/Color;
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.addHtmlColors(MultiMarkdownPlugin.kt:461)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.notifyFeatureUpdate(MultiMarkdownPlugin.kt:552)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.notifyFeatureUpdate(MultiMarkdownPlugin.kt:498)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.initLicense(MultiMarkdownPlugin.kt:393)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.loadLicenseActivation(MultiMarkdownPlugin.kt:294)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.initComponent(MultiMarkdownPlugin.kt:154)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jorisatabix** [comment]
I am having the same issue.

**Comment by vsch** [comment]
@SpencerBrown, @jorisatabix, I removed the release and will release a fixed version in a few minutes.

It is an issue of using API that was added in later IDE releases.

**Comment by vsch** [comment]
@SpencerBrown, @jorisatabix, new version released.

Caused by seemingly insignificant addition of getting the IDE link color for the notification. 

Unfortunately, it happened to be a method added in the API in a later release. JetBrains Open API has no "@since" tags and finding implementation version can only be done via "version annotations" in the source or through crash and burn like in this case.

Sorry for the hassle.

**Comment by SpencerBrown** [comment]
Doesn't crash any more. :)
