### ISSUE TITLE
NoClassDefFoundError: …saaj/util/ByteInputStream on init

### ISSUE THREAD

**Issue by adrianguenter** [vsch/idea-multimarkdown#60]
Two resources are being [referenced on init](https://github.com/vsch/idea-multimarkdown/blob/1.2.0/src/main/java/com/vladsch/idea/multimarkdown/MultiMarkdownPlugin.java#L150) which [don't seem to exist](https://github.com/vsch/idea-multimarkdown/tree/1.2.0/src/main/resources/com/vladsch/idea/multimarkdown) — `PREVIEW_FX_HLJS_STYLESHEET_LIGHT` ("hljs-default**-fx**.css") and `PREVIEW_FX_HLJS_STYLESHEET_DARK` ("hljs-darcula**-fx**.css").

```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/sun/xml/internal/messaging/saaj/util/ByteInputStream
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.<init>(MultiMarkdownPlugin.java:150)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:425)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:502)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:759)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:712)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:729)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:192)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:106)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:102)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:94)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:83)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.messaging.saaj.util.ByteInputStream PluginClassLoader[com.vladsch.idea.multimarkdown, 1.2.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 35 more
```

#### Environment:
```
Linux dev 4.3.0-040300-generic #201511020949 SMP Mon Nov 2 14:50:44 UTC 2015 x86_64 GNU/Linux

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

java version "1.9.0-ea"
Java(TM) SE Runtime Environment (build 1.9.0-ea-b81)
Java HotSpot(TM) 64-Bit Server VM (build 1.9.0-ea-b81, mixed mode)

IDEA Ultimate 15.0 (143.381)
```

**Comment by vsch** [comment]
@adrianguenter, I will try to figure out the problem on your system but it is not a missing resource in the plugin but something strange with the plugin.jar since it is trying to load a class which does not exist but is part of the distribution. The lines in the licenseable version do not correspond to the open source version since the open source does not have licensing capability or the features.

What JetBrains product and what version are you running it in?  If you can give me JRE and OS you are using. Ideally, if you could send me the plugin zip file that you used for the installation. I will be able to figure out more if I compare it to the distribution copy.

There is definitely something off. I am running the plugin in IDEA Ultimate 15 and CE 13,14 & 15, PhpStorm 9 & 10, WebStorm 11 and tried it with PyCharm CE 4.5.4. I tried both the licensed and unlicensed mode of the plugin and everything worked.

**Comment by vsch** [comment]
@adrianguenter double checked and the class which is not found is normally in the rt.jar or classes.jar of the application depending on the version. I'll keep digging to see if I can better understand the issue.

**Comment by vsch** [comment]
@adrianguenter, I think I figured it out. Found some information that the class I was using may not be supported by all os types. I changed the code to use another class and made a new build so we can figure out if this is the issue. You can download the zip here: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.2.1.zip> and please let me know if it fixes the issue.

**Comment by adrianguenter** [comment]
@vsch, sorry for the delayed reply and missing context, because it's probably important — I'm running JDK 9 (EA). I updated the top post with specifics.

**Comment by adrianguenter** [comment]
@vsch confirmed fixed, thanks!
