### ISSUE TITLE
eap: jsBridgeHelperScript: exception

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#630]
```
jsBridgeHelperScript: exception

netscape.javascript.JSException: ReferenceError: Can't find variable: markdownNavigator
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:137)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at com.vladsch.javafx.webview.debugger.DevToolsDebuggerJsBridge.connectJsBridge(DevToolsDebuggerJsBridge.java:106)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel.preparePage(JavaFxHtmlPanel.kt:644)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel.access$preparePage(JavaFxHtmlPanel.kt:95)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel$setHtml$4$3.invoke(JavaFxHtmlPanel.kt:482)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel$setHtml$4$3.invoke(JavaFxHtmlPanel.kt:95)
	at com.vladsch.idea.multimarkdown.util.HelpersKt.timeIt(Helpers.kt:40)
	at com.vladsch.idea.multimarkdown.editor.javafx.WebViewFxRunner$prepareRunnable$$inlined$synchronized$lambda$2.run(WebViewFxRunner.kt:246)
	at com.vladsch.idea.multimarkdown.editor.javafx.OneTimeFxRunnable.run(OneTimeFxRunnable.java:76)
	at com.vladsch.idea.multimarkdown.editor.javafx.WebViewFxRunner.scheduleWorkRaw(WebViewFxRunner.kt:418)
	at com.vladsch.idea.multimarkdown.editor.javafx.WebViewFxRunner.access$scheduleWorkRaw(WebViewFxRunner.kt:52)
	at com.vladsch.idea.multimarkdown.editor.javafx.WebViewFxRunner$myWorkerStateChangeListener$1.changed(WebViewFxRunner.kt:111)
	at com.vladsch.idea.multimarkdown.editor.javafx.WebViewFxRunner$myWorkerStateChangeListener$1.changed(WebViewFxRunner.kt:52)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$0(WebEngine.java:1226)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vsch** [comment]
@bluelovers, my bad. I introduced this when I added a fix for 2016.3 compatibility.

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
