### ISSUE TITLE
java.lang.NullPointerException with HtmlPasteOptionsForm

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#640]
this error happen when **without open any project**

![default](https://user-images.githubusercontent.com/167966/46268494-513f2500-c56d-11e8-96fa-b9446bda800e.png)

```
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.settings.HtmlPasteOptionsForm.updateDocument(HtmlPasteOptionsForm.java:328)
	at com.vladsch.idea.multimarkdown.settings.HtmlPasteOptionsDialog.updateOptions(HtmlPasteOptionsDialog.java:79)
	at com.vladsch.idea.multimarkdown.settings.HtmlPasteOptionsDialog.<init>(HtmlPasteOptionsDialog.java:74)
	at com.vladsch.idea.multimarkdown.settings.HtmlPasteOptionsDialog.showDialog(HtmlPasteOptionsDialog.java:226)
	at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettingsForm.lambda$new$4(MarkdownApplicationSettingsForm.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

```

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
