### ISSUE TITLE
Error: 2018.3 java.lang.Throwable: Component name collision

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#649]
this error happen on welcome window (the window of without open any project)

```
java.lang.Throwable: Component name collision: org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager and class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponentInstance(ComponentManagerImpl.java:411)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$400(ComponentManagerImpl.java:46)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:475)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:264)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$getDefaultProject$4(ProjectManagerImpl.java:350)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:347)
	at com.vladsch.idea.multimarkdown.language.MultiMarkdownFindUsagesProvider.getWordsScanner(MultiMarkdownFindUsagesProvider.java:79)
	at com.intellij.lang.findUsages.LanguageFindUsages.getWordsScanner(LanguageFindUsages.java:66)

```

**Comment by vsch** [comment]
@bluelovers, do you have multiple markdown navigator plugin directories in the IDE support directory?

On OS X it is found under `~/Library/Application Support/{IDE_PATH_SELECTOR}/`. I do not know the location on other OS installations but the equivalent exists.

Where {IDE_PATH_SELECTOR} is an IDE dependent name. For IDEA community 2018.3 it is `IdeaIC2018.3`. 

In there is a sub-directory `idea-multimarkdown` which contains the plugin jars. If a different directory exists which has the same jars then there will be a conflict since both register the same components.

In any case it is an installation issue which you can try and resolve by uninstalling and re-installing the plugin.
