### ISSUE TITLE
ConcurrentModificationException after deleting .md files

### ISSUE THREAD

**Issue by markwoon** [vsch/idea-multimarkdown#65]
FYI, got this after I deleted several .md files:

null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent.clearNamespaces(MultiMarkdownProjectComponent.java:255)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent.access$300(MultiMarkdownProjectComponent.java:65)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$1$1.run(MultiMarkdownProjectComponent.java:221)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$1.run(MultiMarkdownProjectComponent.java:203)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by vsch** [comment]
I will address these for next release. It is in the same are as another bug if too many threads.  The threading is now eliminated, I will see if this issue is still possible in the new implementation. 

Thank you for taking the time to report this.
