### ISSUE TITLE
NoClassDefFoundError on 2019.1 EAP with JBRE

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#704]
I encountered `java.lang.NoClassDefFoundError` using the JBR11 experimental runtime. Preview rendering does not appear to work. Here is the full stack trace:

```
java.lang.NoClassDefFoundError: com/sun/xml/internal/messaging/saaj/util/ByteOutputStream
	at com.vladsch.idea.multimarkdown.editor.swing.SwingHtmlPanel$setHtml$2.invoke(SwingHtmlPanel.kt:164)
	at com.vladsch.idea.multimarkdown.editor.swing.SwingHtmlPanel$setHtml$2.invoke(SwingHtmlPanel.kt:54)
	at kotlin.text.Regex.replace(Regex.kt:157)
	at com.vladsch.idea.multimarkdown.editor.swing.SwingHtmlPanel.setHtml(SwingHtmlPanel.kt:160)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtmlRunner$7.run(PreviewFileEditorBase.kt:706)
	at com.vladsch.plugin.util.TimeIt.logTime(TimeIt.java:38)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.updateHtmlRunner(PreviewFileEditorBase.kt:705)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase.access$updateHtmlRunner(PreviewFileEditorBase.kt:77)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$updateHtml$nextHtmlOrRefreshRequest$1.run(PreviewFileEditorBase.kt:583)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:648)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at com.intellij.cloudConfig.CloudConfigManager.waitDone(CloudConfigManager.java:1371)
	at com.intellij.cloudConfig.CloudConfigManager.getRepositoryPlugins(CloudConfigManager.java:1355)
	at com.intellij.cloudConfig.CloudConfigManager.getInstalledPlugins(CloudConfigManager.java:1330)
	at com.intellij.cloudConfig.CloudConfigManager.updatePlugins(CloudConfigManager.java:1426)
	at com.intellij.cloudConfig.CloudConfigManager.safeUpdatePlugins(CloudConfigManager.java:1380)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$doConnection$11(CloudConfigManager.java:617)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:648)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.messaging.saaj.util.ByteOutputStream PluginClassLoader[com.vladsch.idea.multimarkdown, 2.8.2] com.intellij.ide.plugins.cl.PluginClassLoader@59de24a8
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 55 more
```

Here are the IDE details, please let me know if you need any additional information to reproduce:

```
IntelliJ IDEA 2019.1 Snapshot (Ultimate Edition)
Build #IU-191.5109.14, built on February 6, 2019
IntelliJ IDEA EAP User
Expiration date: March 8, 2019
JRE: 11-ea+96 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-45-generic
```

**Comment by breandan** [comment]
Also got this error on the same version:

```
java.lang.NoSuchMethodError: javafx.scene.web.WebEngine.impl_getDebugger()Lcom/sun/javafx/scene/web/Debugger;
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel$JSBridge.<init>(JavaFxHtmlPanel.kt:1017)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel$1$1$1.run(JavaFxHtmlPanel.kt:219)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vsch** [comment]
@breandan, I see you are running Java 11, that is the cause. In Java 9+ access to the debugger has to be handled differently and I was not prepared for IDE running on JRE higher than 8.

I will fix it. I have not even tried running the IDE on anything but 8.

**Comment by breandan** [comment]
I usually use JRE 8 as well, but I decided to try 2019.1 EAP + JBRE 11 and now I seem to remember Oracle [removed a bunch of APIs](https://cr.openjdk.java.net/~iris/se/9/java-se-9-fr-spec/#APIs-proposed-for-removal) as part of Jigsaw and then [JavaFX was later removed in JDK 11](https://blogs.oracle.com/java-platform-group/the-future-of-javafx-and-other-java-client-roadmap-updates).

![screenshot from 2019-02-13 10-44-05](https://user-images.githubusercontent.com/175716/52723870-4ca76600-2f7c-11e9-818e-1236b569313d.png)

**Comment by vsch** [comment]
@breandan, the removal of JavaFX from the JDK sounds great but for plugins it is a problem. JavaFX has some native libraries which means only one class loader can load them the rest will fail. So either the IDE will need to include JavaFX or the plugins will fail if more than one uses it.

**Comment by breandan** [comment]
cc: @denis-fokin

**Comment by vsch** [comment]
@breandan, do you know if JBRE 11 is available for OS X or does it come only with 2019.1 EAP for linux?

**Comment by breandan** [comment]
AFAIK it is also available for OS X: https://www.jetbrains.com/idea/nextversion/

**Comment by vsch** [comment]
@breandan, thank you. 

I will be adding Java 11 for next release. I am sure it will be a PITA to resolve differences and try to keep a single plugin distribution.

**Comment by vsch** [comment]
@breandan, I got it working quite easily with the bundled JRE 11.

<img width="1935" alt="image" src="https://user-images.githubusercontent.com/10299086/54065704-b79e3280-41f2-11e9-85cf-4751487dccdc.png">

I will soon make an EAP with what I have completed.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
