### ISSUE TITLE
Can not configure toc anymore

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#730]
When trying to configure a toc with
![image](https://user-images.githubusercontent.com/200952/54826292-c7684d00-4caf-11e9-9f02-17dcb76776bb.png)

it fails with
```
java.lang.NullPointerException
	at com.vladsch.idea.multimarkdown.settings.profile.RenderingProfileManager.getInstance(RenderingProfileManager.java:213)
	at com.vladsch.idea.multimarkdown.intentions.toc.TocOptionsRefactoringForm$2.getHighlighter(TocOptionsRefactoringForm.java:247)
	at com.vladsch.idea.multimarkdown.settings.CustomizableEditorTextField.createEditor(CustomizableEditorTextField.java:185)
	at com.intellij.ui.EditorTextField.initEditor(EditorTextField.java:366)
	at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:349)
	at com.vladsch.idea.multimarkdown.settings.CustomizableEditorTextField.addNotify(CustomizableEditorTextField.java:151)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
```

**Comment by vsch** [comment]
@holgerbrandl, project is null at this point in the code. I will check to see what changed to cause this and fix it.

**Comment by vsch** [comment]
@holgerbrandl, my omission. The project is null at this point temporarily until the form is initialized. I forgot to take that into account when cleaning up rendering profiles.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Thanks @vsch for the quick fix.

**Comment by vsch** [comment]
@holgerbrandl, sorry for introducing the bug in the first place. 

It was a hard decision to touch old, stable implementation but it had to be done because it has morphed over the last two years into pachinko code that sent me into a bout of Tourette's every time I tripped over it. When I heard myself say "Who the F codes this way?" about my own code I knew I reached the limit of my tolerance. 😊

**Comment by holgerbrandl** [comment]
Don't feel sorry, rather feel proud that you always manage to provide such amazingly short response/fix times.
