### ISSUE TITLE
Exception from AppUtils.isAppVersionGreaterThan when running on development build of IntelliJ IDEA

### ISSUE THREAD

**Issue by yole** [vsch/idea-multimarkdown#745]
I've tried to install the plugin (both the release build and the latest EAP, build 2.8.4.24) on a development build of IntelliJ IDEA, build number 192.3492. It fails with the following exception (relevant part extracted):

Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.vladsch.plugin.util.AppUtils.isAppVersionGreaterThan(AppUtils.java:43)
	at com.vladsch.plugin.util.AppUtils.isSvgLoadIconAvailable(AppUtils.java:25)
	at com.vladsch.plugin.util.ui.Helpers.<clinit>(Helpers.java:38)
	... 123 more

**Comment by vsch** [comment]
@yole, thank you for the report. 

It is bug in processing app build number. If the build contains only 2 parts or less then this exception will occur.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by yole** [comment]
Thanks! Confirmed fixed.
