### ISSUE TITLE
Toolbar is completely hidden when window is not wide enough

### ISSUE THREAD

**Issue by yole** [vsch/idea-multimarkdown#748]
See attached screenshot. There's plenty of space to show one of the two toolbars, but the layout logic hides both toolbars completely.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/46553/57136058-d9a7d180-6dab-11e9-9303-b8fb25e87a9e.png">

**Comment by vsch** [comment]
@yole, the toolbar is created from two toolbars within a JPanel with g. Both toolbars are created by `ActionManager.createActionToolbar()`.

The standard implementation collapses both toolbars to the single `>>` popup button since both toolbars are bigger than can fit into their allocated space.

I have tried different settings for `ActionToolbarImpl` layout policies but none result in having a toolbar which only puts buttons which don't fit under the `>>` pop up menu.

I will check tool window toolbar implementation which only move buttons that do not fit into the pop up button to see how to implement a more user friendly toolbar.

**Comment by orome** [comment]
This issue is particularly frustrating since in some IDEs (e.g. InteliiJ) they fit, while in others (e.g. WebStorm) — with exactly the same settings — they are entirely hidden. Why would that be?

**Comment by vsch** [comment]
@yole, in settings you can make it hide disabled buttons and it will shorten the toolbar for most conditions.

I will look into having the toolbars collapse more intelligently instead of all the buttons soon.

![image](https://user-images.githubusercontent.com/10299086/62394071-14034500-b53a-11e9-85c3-563b99ca4176.png)

**Comment by orome** [comment]
Missed that somehow! That works. 

(Is there a way to export? The export functionality doesn't seem to do anything, at least not in the selected directory.)

**Comment by vsch** [comment]
@orome, by export you mean `Export Settings` under Manage... in main settings?

![Screenshot_Main_ManageSettings](https://user-images.githubusercontent.com/10299086/62428160-6bd1b580-b6cc-11e9-9d78-96e1922eb788.png)

It will export `markdown-navigator-settings.xml` to the selected location. You can then select this file when doing `Import Settings` and it will import all settings.

I tried it and it works in 2.9.7 and would expect it to work in 2.9.0 and earlier since this code has not changed in a long time.

**Comment by orome** [comment]
Yes, that export. I don't see any file created in the directory I choose (MacOS).

**Comment by vsch** [comment]
@orome, I am also running on OSX and tried exporting to as high as my user home directory and it does export. 

Do you get any exception in the IDE log file?

**Comment by orome** [comment]
I don't see any errors. Where would I find those?

**Comment by vsch** [comment]
Under help > Show Log In Finder then double click the idea.log file and see if there are errors.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/10299086/62503640-08767f00-b7c3-11e9-924d-65890dc291f8.png">

**Comment by vsch** [comment]
@orome, can you try to export to the project directory. This is the default directory selected on export.

**Comment by orome** [comment]
```
2019-08-10 15:07:10,459 [11000417]  ERROR - llij.ide.plugins.PluginManager - Cannot add null object 
java.lang.NullPointerException: Cannot add null object
	at org.jdom.ContentList.checkPreConditions(ContentList.java:200)
	at org.jdom.ContentList.add(ContentList.java:245)
	at org.jdom.ContentList.add(ContentList.java:80)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.jdom.Element.addContent(Element.java:930)
	at com.vladsch.idea.multimarkdown.settings.MdApplicationSettingsForm.lambda$createUIComponents$7(MdApplicationSettingsForm.java:442)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:76)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:76)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:60)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$7(MacOSApplicationProvider.java:149)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:67)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2019-08-10 15:07:10,463 [11000421]  ERROR - llij.ide.plugins.PluginManager - WebStorm 2019.2  Build #WS-192.5728.87 
2019-08-10 15:07:10,463 [11000421]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-08-10 15:07:10,463 [11000421]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2019-08-10 15:07:10,473 [11000431]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Markdown Navigator version: 2.9.7 
2019-08-10 15:07:11,190 [11001148]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2019-08-10 15:06) 
2019-08-10 15:07:53,695 [11043653]   INFO - rationStore.ComponentStoreImpl - Saving appDaemonCodeAnalyzerSettings took 57 ms 
2019-08-10 15:07:53,715 [11043673]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 114 ms 
```
