### ISSUE TITLE
Editor/Code Style/Markdown don't load

### ISSUE THREAD

**Issue by pabloalmunia** [vsch/idea-multimarkdown#836]
Configuration: 

- Webstorm 2020.1 
- Markdown Navigator 3.0.198.72

After Markdown Navigator is installed the config Editor/Code Style/Markdown don't load and show a "loading..." label always.

![image](https://user-images.githubusercontent.com/1365303/78927293-ea25f900-7a9e-11ea-842a-8c2233eaca74.png)

**Comment by vsch** [comment]
@pabloalmunia, later 2020.1 versions removed a resource string from the bundle.

The issue is fixed in EAP release for 2020.1 IDEs.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

Please note the change that EAP channel is for JetBrains licensed plugin and Legacy EAP is for legacy licensing by vladsch.com

**Comment by pabloalmunia** [comment]
Hi, thank, run but I have a new error:

```
java.lang.AssertionError: baseSeq.charAt: 42 != altUnwrapped.charAt: 0
	at com.vladsch.flexmark.util.format.MarkdownParagraph.resolveTrackedOffsetsEdit(MarkdownParagraph.java:239)
	at com.vladsch.flexmark.util.format.MarkdownParagraph.wrapText(MarkdownParagraph.java:155)
	at com.vladsch.flexmark.formatter.FormatterUtils.renderTextBlockParagraphLines(FormatterUtils.java:596)
	at com.vladsch.flexmark.formatter.internal.CoreNodeFormatter.render(CoreNodeFormatter.java:602)
	at com.vladsch.flexmark.formatter.NodeFormattingHandler.render(NodeFormattingHandler.java:15)
	at com.vladsch.flexmark.formatter.Formatter$MainNodeFormatter.renderNode(Formatter.java:984)
	at com.vladsch.flexmark.formatter.Formatter$MainNodeFormatter.renderChildrenNode(Formatter.java:1050)
	at com.vladsch.flexmark.formatter.Formatter$MainNodeFormatter.renderChildren(Formatter.java:997)
	at com.vladsch.flexmark.formatter.internal.CoreNodeFormatter.render(CoreNodeFormatter.java:300)
	at com.vladsch.flexmark.formatter.NodeFormattingHandler.render(NodeFormattingHandler.java:15)
	at com.vladsch.flexmark.formatter.Formatter$MainNodeFormatter.renderNode(Formatter.java:938)
	at com.vladsch.flexmark.formatter.Formatter$MainNodeFormatter.render(Formatter.java:869)
	at com.vladsch.flexmark.formatter.Formatter.render(Formatter.java:250)
	at com.vladsch.md.nav.util.format.MdFormatter$Companion.formatFile(MdFormatter.kt:88)
	at com.vladsch.md.nav.enh.actions.handlers.util.EnhParagraphContext.adjustParagraph(EnhParagraphContext.kt:90)
	at com.vladsch.md.nav.enh.actions.handlers.EnhBackspaceHandler$charDeleted$1.invoke(EnhBackspaceHandler.kt:233)
	at com.vladsch.md.nav.enh.actions.handlers.EnhBackspaceHandler$charDeleted$1.invoke(EnhBackspaceHandler.kt:29)
	at com.vladsch.md.nav.actions.handlers.util.CaretContextInfo$Companion$withContextOr$1.invoke(CaretContextInfo.kt:492)
	at com.vladsch.md.nav.actions.handlers.util.CaretContextInfo$Companion$withContextOr$1.invoke(CaretContextInfo.kt:409)
	at com.vladsch.md.nav.actions.handlers.util.CaretContextInfo$Companion.withContextOrNull(CaretContextInfo.kt:507)
	at com.vladsch.md.nav.actions.handlers.util.CaretContextInfo$Companion.withContextOr(CaretContextInfo.kt:491)
	at com.vladsch.md.nav.enh.actions.handlers.EnhBackspaceHandler.charDeleted(EnhBackspaceHandler.kt:148)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:95)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$null$2(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:205)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:298)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:407)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:307)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:282)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.actions.DeleteSelectionHandler.executeWriteAction(DeleteSelectionHandler.java:46)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:213)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:212)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:25)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:213)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:212)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:516)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:470)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by vsch** [comment]
@pabloalmunia, this one is intermittent and markdown content dependent caused by backspace handler.

If you can give me the markdown paragraph and location of caret when this occurs, I would be grateful since it is impossible to reproduce without specific conditions.

**Comment by colin-bitterfield** [comment]
I had the same issue (I have a paid license). I removed the plugin and the configuration directory from ~/.markdownNavigator and then restarted the IDE and reinstalled the plugin and license and the problem went away (resolved)
