### ISSUE TITLE
Exception in MdPasteHandler

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#870]
The below exception was thrown while I was editing some code. I was not actively editing any markdown code and did not even have a markdown (or AsciiDoc) file open in the editor. I'm pretty sure this happened when I was pasting some Java code into a Kotlin file and IntelliJ IDEA was converting it to Kotlin.

Strangely, IntelliJ IDEA reported this exception as having occurring in the [AsciiDoc Plugin](https://github.com/asciidoctor/asciidoctor-intellij-plugin). But the top line of the stacktrace shows the class `com.vladsch.md.nav.enh.actions.handlers.MdPasteHandler`.  I included an image of the exception reporter to show this.

Markdown Navigator Version 3.0.202.105 (Purchased)

IntelliJ IDEA 2020.2 Beta (Ultimate Edition)
Build #IU-202.6397.20, built on July 15, 2020
IntelliJ IDEA EAP User
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 16275M
Cores: 16

```
com.intellij.diagnostic.PluginException: execute() delegated to original paste handler, Cannot convert the following Java element class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl due to `unexpected symbol class org.jetbrains.kotlin.nj2k.symbols.JKMultiverseMethodSymbol` [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.vladsch.md.nav.enh.actions.handlers.MdPasteHandler.doExecute(MdPasteHandler.java:366)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:888)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Cannot convert the following Java element class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl due to `unexpected symbol class org.jetbrains.kotlin.nj2k.symbols.JKMultiverseMethodSymbol`
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.throwCanNotConvertError(JavaToJKTreeBuilder.kt:1034)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.access$throwCanNotConvertError(JavaToJKTreeBuilder.kt:56)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder$ExpressionTreeMapper.toJK(JavaToJKTreeBuilder.kt:470)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder$ExpressionTreeMapper.toJK(JavaToJKTreeBuilder.kt:164)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.buildTree(JavaToJKTreeBuilder.kt:1015)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:145)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:195)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:28)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/2196944/87878058-f1b74100-c9af-11ea-9524-a625e08f27d0.png)

**Comment by Javaru** [comment]
Experienced in IntelliJ IDEA 2020.2.2 RC (Ultimate Edition) Build #IU-202.7319.45 with Markdown Navigator Enhanced v3.0.202.105, but with a slightly different stacktrace.

```
com.intellij.diagnostic.PluginException: execute() delegated to original paste handler, lateinit property target has not been initialized [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.vladsch.md.nav.enh.actions.handlers.MdPasteHandler.doExecute(MdPasteHandler.java:366)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:890)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property target has not been initialized
	at org.jetbrains.kotlin.nj2k.symbols.JKUniverseFieldSymbol.getTarget(JKFieldSymbol.kt:25)
	at org.jetbrains.kotlin.nj2k.symbols.JKUniverseFieldSymbol.getFieldType(JKFieldSymbol.kt:23)
	at org.jetbrains.kotlin.nj2k.tree.JKFieldAccessExpression.calculateType(expressions.kt:184)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:29)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:29)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt$applyRecursive$1.invoke(treeUtils.kt:62)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:82)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt$applyRecursive$1.invoke(treeUtils.kt:62)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:82)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase$recurse$1.invoke(RecursiveApplicableConversionBase.kt:12)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion$applyRecursive$2.invoke(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.tree.TreeUtilsKt.applyRecursive(treeUtils.kt:84)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:15)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.applyRecursive(MatchBasedConversion.kt:18)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.recurse(RecursiveApplicableConversionBase.kt:27)
	at org.jetbrains.kotlin.nj2k.conversions.AnyWithStringConcatenationConversion.applyToElement(OperatorExpressionConversion.kt:16)
	at org.jetbrains.kotlin.nj2k.conversions.RecursiveApplicableConversionBase.runConversion(RecursiveApplicableConversionBase.kt:18)
	at org.jetbrains.kotlin.nj2k.SequentialBaseConversion$runConversion$1.invoke(BaseConversion.kt:28)
	at org.jetbrains.kotlin.nj2k.SequentialBaseConversion$runConversion$1.invoke(BaseConversion.kt:24)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.maxOrNull(_Sequences.kt:1551)
	at kotlin.sequences.SequencesKt___SequencesKt.max(_Sequences.kt:1278)
	at org.jetbrains.kotlin.nj2k.SequentialBaseConversion$DefaultImpls.runConversion(BaseConversion.kt:28)
	at org.jetbrains.kotlin.nj2k.conversions.MatchBasedConversion.runConversion(MatchBasedConversion.kt:13)
	at org.jetbrains.kotlin.nj2k.ConversionsRunner.doApply(ConversionsRunner.kt:91)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:168)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:197)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:26)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
