### ISSUE TITLE
NoSuchMethodError: 'EditorColorsManager.addEditorColorsListener' since intellij-idea-2022-1

### ISSUE THREAD

**Issue by qwazer** [vsch/idea-multimarkdown#927]
The plugin fails with

```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.colors.EditorColorsManager.addEditorColorsListener(com.intellij.openapi.editor.colors.EditorColorsListener, com.intellij.openapi.Disposable)'
    at com.vladsch.md.nav.MdPlugin.initComponent(MdPlugin.kt:154)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
    at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.run(ComponentManagerImpl.kt:394)
    at com.intellij.idea.ApplicationLoader$prepareStart$1.run(ApplicationLoader.kt:208)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
    at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
```

**Comment by qwazer** [comment]
relates to https://github.com/vsch/idea-multimarkdown/blob/f18cec21960d7f508b5e27ad47e8e3fdd8d3475a/src/main/java/com/vladsch/md/nav/MdPlugin.kt#L153-L154

**Comment by Eriky-git** [comment]
有解决方式了吗 我也遇到同样问题

**Comment by vsch** [comment]
This should be fixed in the latest update release in the JetBrains Marketplace: <https://plugins.jetbrains.com/plugin/7896-markdown-navigator-enhanced/versions/stable/331235>
