### ISSUE TITLE
Constant exception and blank rendering after 1.3.0.1

### ISSUE THREAD

**Issue by axelcostaspena** [vsch/idea-multimarkdown#93]
Happens with any file

String index out of range: -12
java.lang.StringIndexOutOfBoundsException: String index out of range: -12
	at java.lang.String.substring(String.java:1919)
	at kotlin.StringsKt__StringsJVMKt.substring(StringsJVM.kt:136)
	at kotlin.StringsKt.substring(Unknown Source)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkMatcher.computeMatchText(GitHubLinkMatcher.kt:207)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkMatcher$isOnlyLooseMatchValid$2.invoke(GitHubLinkMatcher.kt:84)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkMatcher$isOnlyLooseMatchValid$2.invoke(GitHubLinkMatcher.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:125)
	at kotlin.LazyKt.getValue(Lazy.kt:77)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkMatcher.isOnlyLooseMatchValid(GitHubLinkMatcher.kt)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.getMatchedRefs(GitHubLinkResolver.kt:215)
	at com.vladsch.idea.multimarkdown.util.GitHubLinkResolver.resolve(GitHubLinkResolver.kt:154)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.getLinkTarget(MultiMarkdownLinkRenderer.java:78)
	at com.vladsch.idea.multimarkdown.editor.MultiMarkdownLinkRenderer.renderLink(MultiMarkdownLinkRenderer.java:98)
	at com.vladsch.idea.multimarkdown.editor.resources.JavaFxHtmlGenerator.makeHtmlPage(JavaFxHtmlGenerator.kt:76)
	at com.vladsch.idea.multimarkdown.editor.resources.JavaFxHtmlGenerator.toHtml(JavaFxHtmlGenerator.kt:56)
	at com.vladsch.idea.multimarkdown.editor.MarkdownPreviewFileEditor$HtmlUpdater.run(MarkdownPreviewFileEditor.kt:266)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vsch** [comment]
@axelcostaspena, this one is very strange. Effectively, a file under a vcs root has a file path that does not start with the vcs root path. Not only that, its path is shorter than the vcs root path by 12 characters.

There is something in your current project configuration that I am not taking into account.

Do you have symbolic links within this project's files?  

Can you also try opening a Markdown file in another project? I want to see if this issue is specific to a project or general to your system.

Also the next fix addresses issues of unrecognized submodule vcs roots.  Can you please install that version so that we can eliminate another bug possibly affecting this part of the code. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.2.zip>

**Comment by axelcostaspena** [comment]
Hi @vsch. I'll try the version tomorrow at work. By now I can ensure the exception happened in a project with some content roots being under VCS and some being not, and even happened in several projects with **no** VCS enabled.

**Comment by Dukecz** [comment]
I had same problem as @axelcostaspena, version 1.3.0.2 from link fixed it for me.

**Comment by vsch** [comment]
@Dukecz, thank you for letting me know. I will consider this fix working.

**Comment by vsch** [comment]
Latest interim release with fixes for exceptions and some feature additions <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.9.zip>
