### ISSUE TITLE
pdf export error

### ISSUE THREAD

**Issue by bludwujiang** [vsch/idea-multimarkdown#932]
--When I using export as pdf function error happens:
2023-06-01 18:54:09,752 [ 157896]  ERROR - ns.styling.enh.ExportPdfAction - class org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to class javax.xml.parsers.DocumentBuilderFactory (org.apache.xerces.jaxp.DocumentBuilderFactoryImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @7a765367; javax.xml.parsers.DocumentBuilderFactory is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @eb58e90) 
java.lang.ClassCastException: class org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to class javax.xml.parsers.DocumentBuilderFactory (org.apache.xerces.jaxp.DocumentBuilderFactoryImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @7a765367; javax.xml.parsers.DocumentBuilderFactory is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @eb58e90)

	at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)

	at org.jsoup.helper.W3CDom.<init>(W3CDom.java:65)

	at com.vladsch.md.nav.enh.actions.styling.ExportPdfAction$Companion.exportToPdf(ExportPdfAction.kt:226)

	at com.vladsch.md.nav.enh.actions.styling.ExportPdfAction$Companion.exportToPdf(ExportPdfAction.kt:212)

	at com.vladsch.md.nav.enh.actions.styling.ExportPdfAction.actionPerformed$lambda$4(ExportPdfAction.kt:188)

	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:361)

	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)

	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)

	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)

	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)

	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)

	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)

	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)

	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)

	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:349)

	at com.vladsch.md.nav.enh.actions.styling.ExportPdfAction.actionPerformed(ExportPdfAction.kt:187)

	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:239)

	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:260)

	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:239)

	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:277)

	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)

	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)

	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:269)

	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)

	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$2(ActionMenuItem.java:111)

	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)

	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)

	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:541)

	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:571)

	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)

	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)

	at java.desktop/java.awt.Component.processEvent(Component.java:6419)

	at java.desktop/java.awt.Container.processEvent(Container.java:2263)

	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)

	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)

	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)

	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)

	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)

	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)

	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)

	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)

	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)

	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)

	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)

	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)

	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)

	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)

	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)

	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)

	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)

	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)

	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)

	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)

	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)

	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by bludwujiang** [comment]
I'm on IntelliJ IDEA 2021.3.3 (Ultimate Edition).  Need some help, thanks. @vsch
