### ISSUE TITLE
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.

### ISSUE THREAD

**Issue by mxxcon** [vsch/idea-multimarkdown#95]
I just installed plugin 1.3.0 on PyCharm 5.0.3 and after restarting I get the following popup message:
```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart PyCharm.

java.lang.ExceptionInInitializerError
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion$DEFAULT$2.invoke(MarkdownCssSettings.kt:177)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion$DEFAULT$2.invoke(MarkdownCssSettings.kt:176)
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:125)
    at kotlin.LazyKt.getValue(Lazy.kt:77)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion.getDEFAULT(MarkdownCssSettings.kt)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$SharedState.<init>(MarkdownApplicationSettings.kt:261)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings.<init>(MarkdownApplicationSettings.kt:49)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$Companion.getInstance(MarkdownApplicationSettings.kt:329)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.<init>(MultiMarkdownPlugin.kt:127)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: nullmultimarkdown_darcula.css (Access is denied)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.updateTempCssWithCustomFontCopy(MultiMarkdownPlugin.kt:241)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.createTempCssWithCustomFont(MultiMarkdownPlugin.kt:235)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.createTempCssWithCustomFontExtURL(MultiMarkdownPlugin.kt:222)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.resourceFileURL(MultiMarkdownPlugin.kt:75)
    at com.vladsch.idea.multimarkdown.editor.util.HtmlResource$Companion.resourceFileUrl(HtmlResource.kt:48)
    at com.vladsch.idea.multimarkdown.editor.util.HtmlCssResource.<init>(HtmlCssResource.kt:30)
    at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlCssProvider.<init>(SwingHtmlCssProvider.kt:35)
    at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlCssProvider.<clinit>(SwingHtmlCssProvider.kt:29)
    ... 62 more
```
Upon restarting PyCharm this plugin becomes disabled.

**Comment by vsch** [comment]
@mxxcon, please download <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.2.zip> that addresses this issue. It happens of systems where Java security does not allow creating files in the temp directory directly.

**Comment by mxxcon** [comment]
Yup, that zip works. :+1:

**Comment by tomhamiltonstubber** [comment]
For future users coming to this page, download the most recent version from https://plugins.jetbrains.com/plugin/7896?pr=idea and use that.

**Comment by vsch** [comment]
@tomhamiltonstubber, installing a plugin will not enable it. However, enabling and restart should work.

Can you post the log for the last startup so I can check if there is a reason it will not enable?

It should look something like this:

```
2016-06-16 08:03:32,927 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2016-06-16 08:03:32,947 [     20]   INFO -        #com.intellij.idea.Main - IDE: PyCharm (build #PY-145.1504.1, 25 May 2016 00:00) 
2016-06-16 08:03:32,947 [     20]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (10.10.5, x86_64) 
2016-06-16 08:03:32,947 [     20]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_76-release-b198 (JetBrains s.r.o) 
2016-06-16 08:03:32,947 [     20]   INFO -        #com.intellij.idea.Main - JVM: 25.76-b198 (OpenJDK 64-Bit Server VM) 
2016-06-16 08:03:32,951 [     24]   INFO -        #com.intellij.idea.Main - JVM Args: -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -Xbootclasspath/a:../lib/boot.jar -Xms128m -Xmx750m -XX:MaxPermSize=350m -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djb.vmOptionsFile=/Applications/PyCharm.app/Contents/bin/pycharm.vmoptions -Didea.java.redist=jdk-bundled -Didea.home.path=/Applications/PyCharm.app/Contents -Didea.executable=pycharm -Didea.platform.prefix=Python -Didea.paths.selector=PyCharm2016.1 
2016-06-16 08:03:32,951 [     24]   INFO -        #com.intellij.idea.Main - ext: /Applications/PyCharm.app/Contents/jre/jdk/Contents/Home/jre/lib/ext: [cldrdata.jar, dnsns.jar, jaccess.jar, jfxrt.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunpkcs11.jar, zipfs.jar] 
2016-06-16 08:03:32,951 [     24]   INFO -        #com.intellij.idea.Main - ext: /System/Library/Java/Extensions: [AppleScriptEngine.jar, dns_sd.jar, j3daudio.jar, j3dcore.jar, j3dutils.jar, jai_codec.jar, jai_core.jar, libAppleScriptEngine.jnilib, libJ3D.jnilib, libJ3DAudio.jnilib, libJ3DUtils.jnilib, libmlib_jai.jnilib, mlibwrapper_jai.jar, MRJToolkit.jar, vecmath.jar] 
2016-06-16 08:03:32,951 [     24]   INFO -        #com.intellij.idea.Main - ext: /usr/lib/java: [libjdns_sd.jnilib] 
2016-06-16 08:03:32,951 [     24]   INFO -        #com.intellij.idea.Main - JNU charset: UTF-8 
2016-06-16 08:03:32,964 [     37]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 13 ms 
2016-06-16 08:03:32,967 [     40]   INFO -        #com.intellij.idea.Main - initializing environment 
2016-06-16 08:03:32,968 [     41]   INFO - .intellij.util.EnvironmentUtil - loading shell env: /bin/bash -l -i -c '/Applications/PyCharm.app/Contents/bin/printenv.py' '/private/var/folders/bs/4ktxsyn54pj5mc0l8b43h8vc0000gp/T/intellij-shell-env.tmp' 
2016-06-16 08:03:32,973 [     46]   INFO -     #com.intellij.util.ui.JBUI - UI scale factor: 1.0 
2016-06-16 08:03:33,079 [    152]   INFO - .intellij.util.EnvironmentUtil - shell environment loaded (20 vars) 
2016-06-16 08:03:33,079 [    152]   INFO - .intellij.util.EnvironmentUtil - LC_CTYPE=en_US.UTF-8 
2016-06-16 08:03:33,988 [   1061]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor plugin-intelliLang.xml 
2016-06-16 08:03:34,061 [   1134]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor js-nashorn-support.xml 
2016-06-16 08:03:34,109 [   1182]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-java-support.xml 
2016-06-16 08:03:34,110 [   1183]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-properties-support.xml 
2016-06-16 08:03:34,189 [   1262]   INFO - llij.ide.plugins.PluginManager - Plugin 'CodeGlance' can't be loaded because: Plugin is disabled 
2016-06-16 08:03:34,192 [   1265]   INFO - llij.ide.plugins.PluginManager - Plugin 'Markdown support' can't be loaded because: Plugin is disabled 
2016-06-16 08:03:34,228 [   1301]   INFO - llij.ide.plugins.PluginManager - 54 plugins initialized in 284 ms 
2016-06-16 08:03:34,229 [   1302]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: AngularJS (145.SNAPSHOT), CSS Support (145.SNAPSHOT), CVS Integration (11), CoffeeScript (2.0), Concurrency Visualiser (0.1), Database Tools and SQL (1.0), Django Database Support Integration (1.0), Docker integration (2.1.2), EditorConfig (145.1504.1), File Watchers (145.SNAPSHOT), GNU GetText files support (*.po) (136.SNAPSHOT), Gherkin (999.999), Git Integration (8.1), GitHub (145.1504.1), HAML (145.SNAPSHOT), HTML Tools (2.0), IDEA CORE (145.SNAPSHOT), IPython Notebook (0.1), Ini4Idea (999.999), IntelliLang (8.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), LESS support (145.SNAPSHOT), Perforce Integration (2.0), Puppet Support (VERSION), Python BDD support for engines, based on Gherkin (cucumber, lettuce, behave) (0.1), Python IntelliLang (VERSION), Python JavaScript Debugger Integration (VERSION), Python Localization Integration (VERSION), Python Profiler (0.1), Python ReStructureText Integration (1.0), Python Remote Interpreter (VERSION), Python UML Diagrams (VERSION), REST Client (145.SNAPSHOT), ReStructuredText Support (136.SNAPSHOT), Remote Hosts Access (0.1), SASS support (145.SNAPSHOT), SSH Remote Run (0.1), Settings Repository (145.1504.1), Stylus support (999.999), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TextMate bundles support (VERSION), UML Support (1.0), Vagrant (0.6.VERSION), hg4idea (10.0) 
2016-06-16 08:03:34,229 [   1302]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Markdown Navigator (1.7.1.3), Plugin Developer's Toolbox (1.0.7), PsiViewer (3.28.77), YAML (145.SNAPSHOT) 
2016-06-16 08:03:34,229 [   1302]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: CodeGlance (1.4.4), Markdown support (2016.1.20160405) 
2016-06-16 08:03:34,461 [   1534]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2016-06-16 08:03:34,481 [   1554]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/PyCharm.app/Contents/bin/fsnotifier 
2016-06-16 08:03:34,487 [   1560]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2016-06-16 08:03:34,552 [   1625]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2016-06-16 08:03:34,552 [   1625]   INFO - pi.util.registry.RegistryState -   editor.balloonHints = false 
2016-06-16 08:03:34,553 [   1626]   INFO - pi.util.registry.RegistryState -   editor.caret.width = 1 
2016-06-16 08:03:34,553 [   1626]   INFO - pi.util.registry.RegistryState -   editor.zero.latency.typing = true 
2016-06-16 08:03:34,791 [   1864]   INFO -     #com.intellij.util.ui.JBUI - UI scale factor changed: 1.0 
2016-06-16 08:03:34,875 [   1948]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories:  
2016-06-16 08:03:34,931 [   2004]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2016-06-16 08:03:34,959 [   2032]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2016-06-16 08:03:35,066 [   2139]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index TodoIndex. The index will be rebuilt. 
2016-06-16 08:03:35,139 [   2212]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index IdIndex. The index will be rebuilt. 
2016-06-16 08:03:35,159 [   2232]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index filetypes. The index will be rebuilt. 
2016-06-16 08:03:35,577 [   2650]   INFO - com.vladsch.idea.multimarkdown - migrateSettings using old API 
2016-06-16 08:03:35,624 [   2697]   INFO - plication.impl.ApplicationImpl - 80 application components initialized in 1680 ms 
2016-06-16 08:03:35,648 [   2721]   INFO - .intellij.idea.IdeaApplication - App initialization took 3115 ms 
2016-06-16 08:03:35,876 [   2949]   INFO - ellij.project.impl.ProjectImpl - 15 project components initialized in 64 ms 
2016-06-16 08:03:35,877 [   2950]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2016-06-16 08:03:35,946 [   3019]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@4095e9ed 
2016-06-16 08:03:36,279 [   3352]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@81cd9c3 
2016-06-16 08:03:36,410 [   3483]   INFO - ellij.project.impl.ProjectImpl - 113 project components initialized in 313 ms 
2016-06-16 08:03:36,483 [   3556]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 73 ms 
2016-06-16 08:03:36,727 [   3800]   INFO - ction.BrowserConnectionManager - Browser connected: version 2.0.9, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36 
2016-06-16 08:03:36,942 [   4015]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 11ms; general responsiveness: ok; EDT responsiveness: ok 
2016-06-16 08:03:37,159 [   4232]   INFO - ea.multimarkdown.editor.javafx - standard JavaFx installation has all files for media support, SVG graphics and GitHub page display in preview will be enabled 
2016-06-16 08:03:37,163 [   4236]   INFO - ea.multimarkdown.editor.javafx - ClassLoader urls: [file:/Users/vlad/Library/Preferences/PyCharm2016.1/openjfx/jre/lib/ext/jfxrt.jar, file:/Users/vlad/Library/Preferences/PyCharm2016.1/openjfx/jre/lib/jfxswt.jar, file:/Users/vlad/Library/Preferences/PyCharm2016.1/openjfx/jre/lib/*.dylib, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/asm-all-asm4.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/commons-io-2.4.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/commons-validator-1.4.1.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/idea-multimarkdown-javafx.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/idea-multimarkdown.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/javax.json-1.0.4.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/kotlin-reflect.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/kotlin-runtime.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/Loboevolution.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/parboiled-core-asm4.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/parboiled-java-asm4.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/pegdown-1.6.7.jar, file:/Users/vlad/Library/Application%20Support/PyCharm2016.1/idea-multimarkdown/lib/smart-data.jar] 
2016-06-16 08:03:37,459 [   4532]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 517ms; general responsiveness: ok; EDT responsiveness: ok 
2016-06-16 08:03:37,461 [   4534]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 7975 files to update 
2016-06-16 08:03:38,434 [   5507]   INFO - tartup.impl.StartupManagerImpl - /Users/vlad/src/PycharmProjects/markdown-test/.idea case-sensitivity: expected=false actual=false 
2016-06-16 08:03:42,982 [  10055]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 6912 ms 
2016-06-16 08:03:47,649 [  14722]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 10188ms; general responsiveness: 0/30 sluggish, 20/30 very slow; EDT responsiveness: 2/10 sluggish 
2016-06-16 08:03:54,725 [  21798]   INFO - ns.python.sdk.PythonSdkUpdater - Updating sys.path took 45 ms 
2016-06-16 08:03:54,726 [  21799]   INFO - ns.python.sdk.PythonSdkUpdater - Bogus sys.path entry /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip 
2016-06-16 08:03:54,727 [  21800]   INFO - ns.python.sdk.PythonSdkUpdater - Bogus sys.path entry /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old 
2016-06-16 08:03:54,727 [  21800]   INFO - ns.python.sdk.PythonSdkUpdater - Binary skeletons directory for SDK "Python 2.7.10 (/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7)" (/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7): /Users/vlad/Library/Caches/PyCharm2016.1/python_stubs/-2125986627 
2016-06-16 08:03:54,728 [  21801]   INFO - ns.python.sdk.PythonSdkUpdater - User skeletons directory for SDK "Python 2.7.10 (/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7)" (/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7): /Applications/PyCharm.app/Contents/helpers/python-skeletons 
2016-06-16 08:03:54,747 [  21820]   INFO - ns.python.sdk.PythonSdkUpdater - Performing background update of skeletons for SDK /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 
2016-06-16 08:03:54,748 [  21821]   INFO - .skeletons.PySkeletonRefresher - Refreshing skeletons for /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 
2016-06-16 08:03:55,004 [  22077]   INFO - .skeletons.PySkeletonGenerator - Retrieving binary module list took 246 ms 
2016-06-16 08:03:55,005 [  22078]   INFO - .skeletons.PySkeletonRefresher - Home path is /Applications/PyCharm.app/Contents 
2016-06-16 08:03:55,005 [  22078]   INFO - .skeletons.PySkeletonRefresher - Pregenerated skeletons root is /Applications/PyCharm.app/Contents/skeletons 
2016-06-16 08:03:55,005 [  22078]   INFO - .skeletons.PySkeletonRefresher - Not found pregenerated skeletons at /Applications/PyCharm.app/Contents/skeletons/skeletons-mac-394-10.10-python-2.7.10.zip 
2016-06-16 08:03:55,018 [  22091]   INFO - .skeletons.PySkeletonRefresher - Rebuilding skeletons for binaries took 13 ms 
```
